import Foundation

// MARK: - Color Aliases
private let C = CLR_CYAN
private let D = CLR_DCYAN
private let W = CLR_WHITE
private let B = CLR_BLACK
private let P = CLR_PINK
private let K = CLR_BLUSH
private let O = CLR_OUTLINE
private let Y = CLR_GOLD
private let G = CLR_PURPLE
private let S = CLR_SKYBLUE
private let R = CLR_RED
private let Z = CLR_GRAY
private let T: UInt32? = nil

// MARK: - CatSprites

struct CatSprites: SpriteProvider {
    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return catNormalIdle
        case .normal:   return catNormalWalk
        case .busy:     return catNormalBusy
        case .bloated:  return catNormalBloated
        case .stressed: return catNormalStressed
        case .tired:    return catNormalTired
        case .collab:   return catNormalCollab
        }
    }

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return catBuffIdle
        case .normal:   return catBuffWalk
        case .busy:     return catBuffBusy
        case .bloated:  return catBuffBloated
        case .stressed: return catBuffStressed
        case .tired:    return catBuffTired
        case .collab:   return catBuffCollab
        }
    }

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return catMachoIdle
        case .normal:   return catMachoWalk
        case .busy:     return catMachoBusy
        case .bloated:  return catMachoBloated
        case .stressed: return catMachoStressed
        case .tired:    return catMachoTired
        case .collab:   return catMachoCollab
        }
    }
}

// ============================================================================
// MARK: - Normal Sprites (original v1 cat)
// ============================================================================

// MARK: IDLE: Sleeping cat, curled up, Zzz
private let catNormalIdle: [[[UInt32?]]] = [
    // Frame 0: curled sleeping cat
    [
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: breathing in (slightly bigger body)
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: Zzz shifted
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: breathing out (back to normal)
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4: same as 0 (loop)
    [
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: NORMAL: Walking happy cat
private let catNormalWalk: [[[UInt32?]]] = [
    // Frame 0: stand, left foot forward
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: walk, right foot forward
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: stand center
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: walk left foot back
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4: stand center (same as 2)
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: BUSY: Running fast with sweat
private let catNormalBusy: [[[UInt32?]]] = [
    // Frame 0: stretched run right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,S,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,O,O,T,T,T,T],
        [T,O,T,O,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: mid-stride
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,S,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,O,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,O,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: airborne
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,S,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,O,T,O,D,D,D,D,D,D,O,O,T,T,T,T],
        [T,T,O,O,D,D,D,D,D,D,D,T,O,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: landing
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,S,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,O,T,O,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,O,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4: stretch
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,S,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,O,T,T,T,T],
        [T,O,T,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: BLOATED: Full context, puffy body
private let catNormalBloated: [[[UInt32?]]] = [
    // Frame 0: round puffy cat
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: slight bounce up
    [
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: same as 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: waddle right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,O,C,O,T,T,T,O,C,O,T,T,T],
        [T,T,T,O,C,C,C,O,O,O,C,C,C,O,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,C,C,O,T,T],
        [T,T,T,O,C,W,B,C,C,C,W,B,C,O,T,T],
        [T,T,T,O,C,B,B,C,C,C,B,B,C,O,T,T],
        [T,T,T,O,K,C,C,P,P,C,C,K,C,O,T,T],
        [T,T,T,T,O,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,O,O,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,T,O,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4: same as 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: STRESSED: Shaking with ! above head
private let catNormalStressed: [[[UInt32?]]] = [
    // Frame 0: shake left + !
    [
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,B,W,C,C,B,W,C,O,T,T,T,T,T],
        [T,O,C,B,B,C,C,B,B,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,T,O,O,T,T,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
    ],
    // Frame 1: shake right + !
    [
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,O,C,O,T,T,O,C,O,T,T,T,T],
        [T,T,T,O,C,C,C,O,O,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,B,W,C,C,B,W,C,O,T,T,T],
        [T,T,T,O,C,B,B,C,C,B,B,C,O,T,T,T],
        [T,T,T,O,C,C,C,P,C,C,C,C,O,T,T,T],
        [T,T,T,T,O,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
    ],
    // Frame 2: same as 0
    [
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,B,W,C,C,B,W,C,O,T,T,T,T,T],
        [T,O,C,B,B,C,C,B,B,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,T,O,O,T,T,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
    ],
    // Frame 3: same as 1
    [
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,O,C,O,T,T,O,C,O,T,T,T,T],
        [T,T,T,O,C,C,C,O,O,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,B,W,C,C,B,W,C,O,T,T,T],
        [T,T,T,O,C,B,B,C,C,B,B,C,O,T,T,T],
        [T,T,T,O,C,C,C,P,C,C,C,C,O,T,T,T],
        [T,T,T,T,O,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
    ],
    // Frame 4: ! shifted left
    [
        [T,T,T,T,T,T,R,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,R,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,B,W,C,C,B,W,C,O,T,T,T,T,T],
        [T,O,C,B,B,C,C,B,B,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,T,T,O,O,T,T,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
    ],
]

// MARK: TIRED: Slouched, half-closed eyes
private let catNormalTired: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: shuffle
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: same as 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: COLLAB: Two small cats walking together
private let catNormalCollab: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,T,T,T,O,T,T,T,O,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: offset walk
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,T,O,T,O,T,T,T,T,T,O,T,O,T,T,T],
        [T,T,T,O,T,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: same as 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,T,T,T,O,T,T,T,O,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [O,T,T,T,O,T,T,T,O,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4: same as 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,D,O,T,T,T,T,T,O,D,O,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,T,T,T,O,T,T,T,O,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// ============================================================================
// MARK: - Buff Sprites (wider body, broader shoulders, same head)
// ============================================================================

// MARK: Buff IDLE: Sleeping buff cat
private let catBuffIdle: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4
    [
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,O,O,C,C,O,O,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,P,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: Buff WALK: Walking buff cat with wider shoulders
private let catBuffWalk: [[[UInt32?]]] = [
    // Frame 0: stand, left foot forward
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,O,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,O,O,T,T,T,T,O,O,T,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1: walk, right foot forward
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,O,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,T,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: stand center
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,O,O,O,T,T,T,O,O,O,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: walk left foot back
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,O,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,T,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4: stand center
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,O,O,O,T,T,T,O,O,O,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: Buff BUSY: Running buff cat with sweat
private let catBuffBusy: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,S,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,O,T,T],
        [T,O,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,O,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,T,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,S,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,S,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,O,D,D,D,D,D,D,D,D,D,O,O,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,T,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,O,T,T,T,T,T,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,S,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,S,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,C,B,W,C,C,C,B,W,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,O,T,T],
        [T,O,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,O,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,T,O,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: Buff BLOATED: Puffy buff cat
private let catBuffBloated: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,O,O,O,T,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,O,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1
    [
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,O,O,O,T,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,O,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,O,O,O,T,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,O,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: waddle right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,O,C,O,T,T,T,O,C,O,T,T,T],
        [T,T,T,O,C,C,C,O,O,O,C,C,C,O,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,C,C,O,T,T],
        [T,T,T,O,C,W,B,C,C,C,W,B,C,O,T,T],
        [T,T,T,O,C,B,B,C,C,C,B,B,C,O,T,T],
        [T,T,T,O,K,C,C,P,P,C,C,K,C,O,T,T],
        [T,T,T,T,O,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,D,D,O],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,D,D,O],
        [T,T,O,O,O,O,T,T,T,T,T,T,O,O,O,T],
        [T,T,T,T,T,O,T,T,T,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,W,B,C,C,C,W,B,C,O,T,T,T],
        [T,T,O,C,B,B,C,C,C,B,B,C,O,T,T,T],
        [T,T,O,K,C,C,P,P,C,C,K,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,O,O,O,T,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,O,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: Buff STRESSED: Shaking buff cat with !
private let catBuffStressed: [[[UInt32?]]] = [
    // Frame 0: shake left
    [
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,B,W,C,C,B,W,C,O,T,T,T,T,T],
        [T,O,C,B,B,C,C,B,B,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,T,O,T,T,T,T,T,T],
    ],
    // Frame 1: shake right
    [
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,O,C,O,T,T,O,C,O,T,T,T,T],
        [T,T,T,O,C,C,C,O,O,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,B,W,C,C,B,W,C,O,T,T,T],
        [T,T,T,O,C,B,B,C,C,B,B,C,O,T,T,T],
        [T,T,T,O,C,C,C,P,C,C,C,C,O,T,T,T],
        [T,T,T,T,O,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,T,O,O,O,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,T,O,T,T,T,T],
    ],
    // Frame 2: shake left
    [
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,R,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,B,W,C,C,B,W,C,O,T,T,T,T,T],
        [T,O,C,B,B,C,C,B,B,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,T,O,T,T,T,T,T,T],
    ],
    // Frame 3: shake right
    [
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,R,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,O,C,O,T,T,O,C,O,T,T,T,T],
        [T,T,T,O,C,C,C,O,O,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,B,W,C,C,B,W,C,O,T,T,T],
        [T,T,T,O,C,B,B,C,C,B,B,C,O,T,T,T],
        [T,T,T,O,C,C,C,P,C,C,C,C,O,T,T,T],
        [T,T,T,T,O,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,T,O,O,O,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,T,O,T,T,T,T],
    ],
    // Frame 4: ! shifted
    [
        [T,T,T,T,T,T,R,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,R,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,O,T,T,T,T,T,T,T],
        [T,T,O,C,O,T,T,O,C,O,T,T,T,T,T,T],
        [T,O,C,C,C,O,O,C,C,C,O,T,T,T,T,T],
        [T,O,C,C,C,C,C,C,C,C,O,T,T,T,T,T],
        [T,O,C,B,W,C,C,B,W,C,O,T,T,T,T,T],
        [T,O,C,B,B,C,C,B,B,C,O,T,T,T,T,T],
        [T,O,C,C,C,P,C,C,C,C,O,T,T,T,T,T],
        [T,T,O,C,C,C,C,C,C,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
        [T,T,T,O,T,T,T,T,T,O,T,T,T,T,T,T],
    ],
]

// MARK: Buff TIRED: Slouched buff cat
private let catBuffTired: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,O,O,T,T,T,O,O,O,T,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,O,O,T,T,T,O,O,O,T,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,O,C,O,T,T,T,O,C,O,T,T,T,T],
        [T,T,O,C,C,C,O,O,O,C,C,C,O,T,T,T],
        [T,T,O,C,C,C,C,C,C,C,C,C,O,T,T,T],
        [T,T,O,C,O,O,C,C,C,O,O,C,O,T,T,T],
        [T,T,O,C,C,B,C,C,C,C,B,C,O,T,T,T],
        [T,T,O,C,C,C,P,C,C,C,C,C,O,T,T,T],
        [T,T,T,O,C,C,C,C,C,C,C,O,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,O,O,T,T,T,O,O,O,T,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// MARK: Buff COLLAB: Two buff cats walking together
private let catBuffCollab: [[[UInt32?]]] = [
    // Frame 0
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,O,T,T,T,T,O,D,O,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,O,T,T,O,T,T,T,T,O,T,T,O,T,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 1
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,O,T,T,T,T,O,D,O,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,T,O,T,T,O,T,T,T,T,O,T,T,O,T,T],
        [T,T,T,O,T,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,O,T,T,T,T,O,D,O,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,O,T,T,O,T,T,T,T,O,T,T,O,T,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,O,T,T,T,T,O,D,O,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 4
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,T,O,T,T,T,T,T,O,T,O,T,T,T,T],
        [O,C,O,C,O,T,T,T,O,C,O,C,O,T,T,T],
        [O,C,C,C,O,T,T,T,O,C,C,C,O,T,T,T],
        [O,B,C,B,O,T,T,T,O,B,C,B,O,T,T,T],
        [O,C,P,C,O,T,T,T,O,C,P,C,O,T,T,T],
        [T,O,C,O,T,T,T,T,T,O,C,O,T,T,T,T],
        [T,O,D,O,O,T,T,T,T,O,D,O,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,O,T,T,O,T,T,T,T,O,T,T,O,T,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
]

// ============================================================================
// MARK: - Macho Sprites (absurdly large body, tiny head, huge arms, gold sparkles)
// ============================================================================

// MARK: Macho IDLE: Sleeping macho cat with sparkles
private let catMachoIdle: [[[UInt32?]]] = [
    // Frame 0: sparkle top-left
    [
        [Y,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
        [T,T,T,T,O,T,T,O,T,Z,T,T,T,T,T,T],
        [T,T,T,O,C,O,O,C,O,T,T,T,T,T,T,T],
        [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,P,C,O,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: sparkle top-right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,Y],
        [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,O,T,T,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,O,O,C,O,T,T,T,T,T,T,T],
        [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,P,C,O,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: sparkle bottom-right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
        [T,T,T,T,O,T,T,O,T,T,T,Z,T,T,T,T],
        [T,T,T,O,C,O,O,C,O,T,T,T,T,T,T,T],
        [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,P,C,O,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: sparkle bottom-left
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
        [T,T,T,T,O,T,T,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,O,O,C,O,T,T,T,T,T,T,T],
        [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,P,C,O,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: sparkle top-left (loop)
    [
        [Y,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
        [T,T,T,T,O,T,T,O,T,Z,T,T,T,T,T,T],
        [T,T,T,O,C,O,O,C,O,T,T,T,T,T,T,T],
        [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,P,C,O,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,O,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,O,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]

// MARK: Macho WALK: Walking macho cat - huge body, tiny head
private let catMachoWalk: [[[UInt32?]]] = [
    // Frame 0: stand, sparkle top-left
    [
        [Y,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,O,O,T,T,T,T,T,T,T,T,T,O,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: walk right, sparkle top-right
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,Y],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: stand center, sparkle bottom-right
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,Y],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: walk left, sparkle bottom-left
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [Y,O,O,T,T,T,T,T,T,T,T,T,O,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: stand center, sparkle top-left (loop)
    [
        [Y,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,O,O,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]

// MARK: Macho BUSY: Running macho cat with sweat and sparkles
private let catMachoBusy: [[[UInt32?]]] = [
    // Frame 0: sparkle top-left
    [
        [Y,T,T,T,T,T,O,T,O,T,T,T,T,S,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,O,O,T,T,T,T,T,T,T,T,T,O,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: sparkle top-right
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,Y],
        [T,T,T,T,T,O,C,O,C,O,T,S,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: airborne, sparkle bottom-right
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,S,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,T,T,T,T,T,T,T,T,T,O,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: landing, sparkle bottom-left
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,S,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: stretch, sparkle top-left
    [
        [Y,T,T,T,T,T,O,T,O,T,T,T,S,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,B,C,B,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,O,O,T,T,T,T,T,T,T,T,T,O,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]

// MARK: Macho BLOATED: Puffy macho cat
private let catMachoBloated: [[[UInt32?]]] = [
    // Frame 0: sparkle top-left
    [
        [Y,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,W,C,W,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: bounce up, sparkle top-right
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,Y],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,W,C,W,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,O,O,T,T,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: same as 0, sparkle bottom-right
    [
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,W,C,W,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: waddle right, sparkle bottom-left
    [
        [T,T,T,T,T,T,T,O,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,O,C,O,C,O,T,T,T,T,T],
        [T,T,T,T,T,T,O,W,C,W,O,T,T,T,T,T],
        [T,T,T,T,T,T,O,C,P,C,O,T,T,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,D,D,O],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,D,D,O],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,D,D,O],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,D,D,O],
        [T,T,O,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,O,O,T,T,T,T,T,O,O,O,T,T],
        [T,T,T,T,T,O,T,T,T,T,T,O,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: same as 0, sparkle top-left
    [
        [Y,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,W,C,W,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,T,T,O,T,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]

// MARK: Macho STRESSED: Shaking macho cat with !
private let catMachoStressed: [[[UInt32?]]] = [
    // Frame 0: shake left, sparkle top-left
    [
        [Y,T,T,T,T,R,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,R,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,O,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,O,C,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,B,C,B,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,C,O,T,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,O,T,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
        [T,T,O,T,T,T,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: shake right, sparkle top-right
    [
        [T,T,T,T,T,T,T,T,T,R,T,T,T,T,T,Y],
        [T,T,T,T,T,T,T,T,T,R,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,O,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,O,C,O,C,O,T,T,T,T],
        [T,T,T,T,T,T,T,O,B,C,B,O,T,T,T,T],
        [T,T,T,T,T,T,T,O,C,P,C,O,T,T,T,T],
        [T,T,T,T,T,T,O,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,T,T,O,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,T,T,O,O,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,O,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: shake left, sparkle bottom-right
    [
        [T,T,T,T,T,R,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,R,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,O,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,O,C,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,B,C,B,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,C,O,T,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,O,T,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
        [T,T,O,T,T,T,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: shake right, sparkle bottom-left
    [
        [T,T,T,T,T,T,T,T,T,R,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,R,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,O,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,O,C,O,C,O,T,T,T,T],
        [T,T,T,T,T,T,T,O,B,C,B,O,T,T,T,T],
        [T,T,T,T,T,T,T,O,C,P,C,O,T,T,T,T],
        [T,T,T,T,T,T,O,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,O,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,O,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,T,T,T,T,O,D,D,D,D,D,D,O,T,T,T],
        [T,T,T,T,T,T,O,O,T,T,O,O,T,T,T,T],
        [T,T,T,T,T,T,O,T,T,T,T,O,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: ! shifted, sparkle top-left
    [
        [Y,T,T,T,T,T,R,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,R,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,O,T,O,T,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,O,C,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,B,C,B,O,T,T,T,T,T,T,T,T],
        [T,T,T,O,C,P,C,O,T,T,T,T,T,T,T,T],
        [T,T,O,D,D,D,D,D,O,T,T,T,T,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,O,T,T,T,T,T],
        [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
        [T,T,O,T,T,T,T,T,T,O,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]

// MARK: Macho TIRED: Slouching macho cat
private let catMachoTired: [[[UInt32?]]] = [
    // Frame 0: sparkle top-left
    [
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,O,C,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,O,O,T,T,T,T,T,T,T,T,T,O,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: shuffle, sparkle top-right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,O,C,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: same as 0, sparkle bottom-right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,O,C,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,O,O,T,T,T,T,T,T,T,T,T,O,O,T,Y],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: shuffle, sparkle bottom-left
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,O,C,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,T,T,T,T,T,T,O,O,T,T,T,T],
        [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        [Y,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: sparkle top-left
    [
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,O,C,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,O,C,O,O,T,T,T,T,T,T],
        [T,T,T,T,T,O,C,P,C,O,T,T,T,T,T,T],
        [T,T,T,O,D,D,D,D,D,D,D,O,T,T,T,T],
        [T,T,O,D,D,D,D,D,D,D,D,D,O,T,T,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [O,D,D,D,D,D,D,D,D,D,D,D,D,D,O,T],
        [T,O,D,D,D,D,D,D,D,D,D,D,D,O,T,T],
        [T,T,O,O,O,T,T,T,T,T,O,O,O,T,T,T],
        [T,T,O,O,T,T,T,T,T,T,T,O,O,T,T,T],
        [T,O,O,T,T,T,T,T,T,T,T,T,O,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]

// MARK: Macho COLLAB: Two macho cats together
private let catMachoCollab: [[[UInt32?]]] = [
    // Frame 0: sparkle top-left
    [
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,O,T,T,T,T,T,T,O,O,T,T,T,T,T],
        [O,C,C,O,T,T,T,T,O,C,C,O,T,T,T,T],
        [O,B,B,O,T,T,T,T,O,B,B,O,T,T,T,T],
        [O,C,P,O,T,T,T,T,O,C,P,O,T,T,T,T],
        [O,D,D,D,O,T,T,T,O,D,D,D,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,O,D,D,O,T,T,T,T,O,D,D,O,T,T,T],
        [T,O,T,T,O,T,T,T,T,O,T,T,O,T,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 1: offset walk, sparkle top-right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,O,T,T,T,T,T,T,O,O,T,T,T,T,T],
        [O,C,C,O,T,T,T,T,O,C,C,O,T,T,T,T],
        [O,B,B,O,T,T,T,T,O,B,B,O,T,T,T,T],
        [O,C,P,O,T,T,T,T,O,C,P,O,T,T,T,T],
        [O,D,D,D,O,T,T,T,O,D,D,D,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,T,O,T,T,O,T,T,T,T,O,T,T,O,T,T],
        [T,T,T,O,T,T,T,T,T,T,T,O,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 2: same as 0, sparkle bottom-right
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,O,T,T,T,T,T,T,O,O,T,T,T,T,T],
        [O,C,C,O,T,T,T,T,O,C,C,O,T,T,T,T],
        [O,B,B,O,T,T,T,T,O,B,B,O,T,T,T,T],
        [O,C,P,O,T,T,T,T,O,C,P,O,T,T,T,T],
        [O,D,D,D,O,T,T,T,O,D,D,D,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,O,D,D,O,T,T,T,T,O,D,D,O,T,T,T],
        [T,O,T,T,O,T,T,T,T,O,T,T,O,T,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
    ],
    // Frame 3: offset, sparkle bottom-left
    [
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,O,T,T,T,T,T,T,O,O,T,T,T,T,T],
        [O,C,C,O,T,T,T,T,O,C,C,O,T,T,T,T],
        [O,B,B,O,T,T,T,T,O,B,B,O,T,T,T,T],
        [O,C,P,O,T,T,T,T,O,C,P,O,T,T,T,T],
        [O,D,D,D,O,T,T,T,O,D,D,D,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
    // Frame 4: same as 0, sparkle top-left
    [
        [Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,O,O,T,T,T,T,T,T,O,O,T,T,T,T,T],
        [O,C,C,O,T,T,T,T,O,C,C,O,T,T,T,T],
        [O,B,B,O,T,T,T,T,O,B,B,O,T,T,T,T],
        [O,C,P,O,T,T,T,T,O,C,P,O,T,T,T,T],
        [O,D,D,D,O,T,T,T,O,D,D,D,O,T,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [O,D,D,D,D,O,T,T,O,D,D,D,D,O,T,T],
        [T,O,D,D,O,T,T,T,T,O,D,D,O,T,T,T],
        [T,O,T,T,O,T,T,T,T,O,T,T,O,T,T,T],
        [O,T,T,T,T,O,T,T,O,T,T,T,T,O,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y],
    ],
]
