import Foundation

// MARK: - Color Aliases
private let Y: UInt32? = CLR_YELLOW   // Body
private let D: UInt32? = CLR_GOLD     // Body shading
private let O: UInt32? = CLR_ORANGE   // Beak / feet
private let B: UInt32? = CLR_BLACK    // Eyes
private let P: UInt32? = CLR_PINK     // Blush
private let W: UInt32? = CLR_WHITE    // Eye highlights
private let K: UInt32? = CLR_BLUSH    // Wing tips
private let G: UInt32? = CLR_GOLD     // Macho sparkle
private let S: UInt32? = CLR_SKYBLUE  // Sweat
private let R: UInt32? = CLR_RED      // Stress
private let Z: UInt32? = CLR_GRAY     // Zzz
private let T: UInt32? = nil          // Transparent

// MARK: - ChickSprites

struct ChickSprites: SpriteProvider {

    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    // ───────────────────────────────────────────────
    // MARK: - Normal (tiny round chick)
    // ───────────────────────────────────────────────

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return normalIdle
        case .normal:   return normalNormal
        case .busy:     return normalBusy
        case .bloated:  return normalBloated
        case .stressed: return normalStressed
        case .tired:    return normalTired
        case .collab:   return normalCollab
        }
    }

    // -- idle: sleeping chick, Zzz --
    private static let normalIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- normal: happy walking chick --
    private static let normalNormal: [[[UInt32?]]] = [
        // Frame 1 – left step
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – right step
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – bounce up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – left step mirror
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – bounce down
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- busy: typing / pecking chick --
    private static let normalBusy: [[[UInt32?]]] = [
        // Frame 1 – peck down
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,O,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – peck up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – peck down wing flap
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,O,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – peck up wing flap
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – peck down fast
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,O,O,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- bloated: puffed up, context full --
    private static let normalBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,B,W,Y,Y,B,W,Y,Y,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,Y,Y,Y,Y,O,O,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,Y,P,Y,Y,P,Y,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,B,W,Y,Y,B,W,Y,Y,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,K,Y,Y,Y,Y,O,O,Y,Y,Y,Y,K,T,T],
            [T,T,T,Y,Y,Y,P,Y,Y,P,Y,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – puff more
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,B,W,Y,Y,B,W,Y,Y,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,Y,Y,Y,Y,O,O,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,Y,P,Y,Y,P,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,B,W,Y,Y,B,W,Y,Y,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,K,Y,Y,Y,Y,O,O,Y,Y,Y,Y,K,T,T],
            [T,T,T,Y,Y,Y,P,Y,Y,P,Y,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,B,W,Y,Y,B,W,Y,Y,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,Y,Y,Y,Y,O,O,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,Y,P,Y,Y,P,Y,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- stressed: sweat drops, shaking --
    private static let normalStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,S,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,R,Y,Y,Y,R,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – shake right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,Y,Y,S,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T],
            [T,T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T],
            [T,T,T,T,T,T,R,Y,Y,Y,R,Y,T,T,T,T],
            [T,T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,T,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – sweat drop lower
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,S,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,R,Y,Y,Y,R,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – shake left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,T,S,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,Y,B,W,Y,Y,B,W,Y,Y,T,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,R,Y,Y,Y,R,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,S,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,R,Y,Y,Y,R,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- tired: droopy, slow --
    private static let normalTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – droops
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – droops more
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- collab: two chicks / happy wings --
    private static let normalCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – wings up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,K,T,Y,Y,Y,Y,Y,Y,Y,Y,T,K,T,T],
            [T,T,K,T,Y,B,W,Y,Y,B,W,Y,T,K,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – wings high
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,K,T,T,Y,Y,Y,Y,Y,Y,T,T,K,T,T],
            [T,T,K,T,Y,Y,Y,Y,Y,Y,Y,Y,T,K,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – wings down
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – wings mid
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,K,Y,Y,Y,Y,Y,Y,Y,Y,K,T,T,T],
            [T,T,T,K,Y,B,W,Y,Y,B,W,Y,K,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,P,Y,Y,P,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ───────────────────────────────────────────────
    // MARK: - Buff (wings become arms, wider chest)
    // ───────────────────────────────────────────────

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return buffIdle
        case .normal:   return buffNormal
        case .busy:     return buffBusy
        case .bloated:  return buffBloated
        case .stressed: return buffStressed
        case .tired:    return buffTired
        case .collab:   return buffCollab
        }
    }

    // -- buff idle --
    private static let buffIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Z,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- buff normal: walking with arms --
    private static let buffNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – bounce
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- buff busy --
    private static let buffBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- buff bloated --
    private static let buffBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,P,Y,Y,P,Y,Y,Y,Y,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- buff stressed --
    private static let buffStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,S,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,R,Y,Y,Y,R,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,Y,B,W,Y,S,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T],
            [T,T,T,T,T,Y,R,Y,Y,Y,R,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,T,Y,D,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,T,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,S,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,R,Y,Y,Y,R,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,S,T,T,T],
            [T,T,T,Y,B,W,Y,Y,B,W,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T,T],
            [T,T,T,Y,R,Y,Y,Y,R,Y,Y,T,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T,T],
            [T,T,T,T,D,D,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,S,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,R,Y,Y,Y,R,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- buff tired --
    private static let buffTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,D,D,D,D,D,D,D,Y,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,D,D,Y,Y,D,D,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- buff collab --
    private static let buffCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – arms up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,Y,T,Y,Y,Y,Y,Y,Y,Y,Y,T,Y,T,T],
            [T,T,Y,T,Y,Y,Y,O,O,Y,Y,Y,T,Y,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – arms high
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,Y,T,Y,B,W,Y,Y,B,W,Y,T,Y,T,T],
            [T,T,Y,T,Y,Y,Y,Y,Y,Y,Y,Y,T,Y,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,Y,T,Y,Y,Y,Y,Y,Y,Y,Y,T,Y,T,T],
            [T,T,Y,T,Y,Y,Y,O,O,Y,Y,Y,T,Y,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,Y,T,T,T,T],
            [T,T,T,T,Y,Y,P,Y,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ───────────────────────────────────────────────
    // MARK: - Macho (absurdly buff, huge pecs, gold sparkles)
    // ───────────────────────────────────────────────

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return machoIdle
        case .normal:   return machoNormal
        case .busy:     return machoBusy
        case .bloated:  return machoBloated
        case .stressed: return machoStressed
        case .tired:    return machoTired
        case .collab:   return machoCollab
        }
    }

    // -- macho idle --
    private static let machoIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,Z,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,Z,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,Z,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,Z,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,Z,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Z,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- macho normal: strutting with sparkles --
    private static let machoNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,G,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,G,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – bounce
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,G,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,G,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,G,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- macho busy --
    private static let machoBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- macho bloated --
    private static let machoBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,Y,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,Y,T],
            [T,T,Y,Y,Y,D,D,D,D,D,D,Y,Y,Y,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,Y,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,Y,T],
            [T,T,Y,Y,Y,D,D,D,D,D,D,Y,Y,Y,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,Y,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,Y,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,Y,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,Y,T],
            [T,T,Y,Y,Y,D,D,D,D,D,D,Y,Y,Y,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,Y,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,Y,T],
            [T,T,Y,Y,Y,D,D,D,D,D,D,Y,Y,Y,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- macho stressed --
    private static let machoStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,S,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,R,Y,Y,R,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – shake right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,Y,Y,S,T,T,T],
            [T,T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T],
            [T,T,T,T,T,T,Y,R,Y,Y,R,Y,Y,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T],
            [T,T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T],
            [T,T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T],
            [T,T,T,T,T,T,D,D,D,D,D,D,T,T,T,T],
            [T,T,T,T,T,T,T,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,S,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,R,Y,Y,R,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – shake left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,Y,Y,Y,T,S,T,T,T,T],
            [T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T,T],
            [T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,T,Y,R,Y,Y,R,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,Y,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,Y,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,D,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,S,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,R,Y,Y,R,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- macho tired --
    private static let machoTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,D,D,D,D,D,D,D,D,Y,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,D,D,D,D,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,O,O,Y,Y,T,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,Y,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- macho collab: flexing with sparkles --
    private static let machoCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,G,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – flex up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,G,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,Y,T,T,Y,Y,Y,O,O,Y,Y,T,T,Y,T],
            [T,T,Y,T,T,Y,Y,P,Y,P,Y,Y,T,T,Y,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – flex max
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,G,T,T],
            [T,T,Y,T,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,Y,T,T,Y,Y,Y,Y,Y,Y,T,T,Y,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,Y,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – flex down
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,Y,Y,Y,Y,T,T,T,G,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,T,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,Y,T,T,Y,Y,Y,O,O,Y,Y,T,T,Y,T],
            [T,T,Y,T,T,Y,Y,P,Y,P,Y,Y,T,T,Y,T],
            [T,T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,T,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,G,T,T,Y,Y,Y,Y,T,T,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,Y,Y,Y,T,G,T,T,T],
            [T,T,T,T,T,Y,B,W,Y,B,W,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,Y,O,O,Y,Y,T,T,T,T],
            [T,T,T,T,T,Y,Y,P,Y,P,Y,Y,T,T,T,T],
            [T,T,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,T],
            [T,T,T,Y,D,Y,Y,Y,Y,Y,Y,D,Y,Y,T,T],
            [T,T,Y,D,D,Y,Y,Y,Y,Y,Y,D,D,Y,T,T],
            [T,T,T,Y,Y,D,D,D,D,D,D,Y,Y,T,T,T],
            [T,T,T,T,T,D,D,D,D,D,D,T,T,T,T,T],
            [T,T,T,T,T,T,D,D,D,D,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]
}
