import Foundation

// MARK: - Fox Color Aliases
private let O = CLR_ORANGE   // Body
private let D = CLR_DORANGE  // Body shading
private let W = CLR_WHITE    // Chest / tail tip
private let B = CLR_BLACK    // Legs / ears / eyes
private let Y = CLR_GOLD     // Eyes / macho sparkle
private let N = CLR_DBROWN   // Nose
private let P = CLR_PINK     // Inner ears
private let S = CLR_SKYBLUE  // Sweat
private let R = CLR_RED      // Stress
private let Z = CLR_GRAY     // Zzz
private let T: UInt32? = nil  // Transparent

// MARK: - FoxSprites

struct FoxSprites: SpriteProvider {
    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    // ──────────────────────────────────────────────
    // MARK: - Normal  (slender sly fox)
    // ──────────────────────────────────────────────

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return normalIdle
        case .normal:   return normalWalk
        case .busy:     return normalBusy
        case .bloated:  return normalBloated
        case .stressed: return normalStressed
        case .tired:    return normalTired
        case .collab:   return normalCollab
        }
    }

    // --- idle (sleeping fox curled up) ---
    private static let normalIdle: [[[UInt32?]]] = [
        // Frame 1 – curled, Zzz small
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,W,W,W,W,W,W,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,O,O,O,O,D,W,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
        ],
        // Frame 2 – Zzz rises
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,W,W,W,W,W,W,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,O,O,O,O,D,W,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
        ],
        // Frame 3 – Zzz higher
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,W,W,W,W,W,W,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,O,O,O,O,D,W,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
        ],
        // Frame 4 – Zzz fades, tail twitches
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,W,W,W,W,W,W,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,O,O,O,O,W,D,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
        ],
        // Frame 5 – back to start cycle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,W,W,W,W,W,W,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,O,O,O,O,D,W,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
        ],
    ]

    // --- normal (walking fox, legs cycle) ---
    private static let normalWalk: [[[UInt32?]]] = [
        // Frame 1 – standing, legs even
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – left legs forward
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,B,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – mid stride
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,B,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,B,T,T,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – right legs forward
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – returning to stand
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- busy (working hard, ears alert, typing) ---
    private static let normalBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,B,T,T,T],
            [T,T,T,B,D,O,W,W,W,W,O,D,B,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – paws up typing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,B,O,O,O,O,O,O,B,B,T,T,T],
            [T,T,T,T,B,O,W,W,W,W,O,B,T,T,T,T],
            [T,T,T,T,B,D,W,W,W,W,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – arms alternate
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,B,T,T,T],
            [T,T,T,B,D,O,W,W,W,W,O,D,B,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – paws up again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,B,B,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,W,W,W,W,O,B,B,T,T,T],
            [T,T,T,T,B,D,W,W,W,W,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,B,T,T,T],
            [T,T,T,B,D,O,W,W,W,W,O,D,B,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- bloated (puffed up, context full) ---
    private static let normalBloated: [[[UInt32?]]] = [
        // Frame 1 – puffed body
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,O,O,W,W,W,O,O,D,B,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – even puffier
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,O,O,O,W,W,W,O,O,O,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – belly breathe in
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,O,O,W,W,W,O,O,D,B,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – puffed again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,O,O,O,W,W,W,O,O,O,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – settle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,O,O,W,W,W,O,O,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- stressed (rate limit, sweat, red face) ---
    private static let normalStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,S,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – sweat drop falls
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,S,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – shaking
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,B,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,R,Y,Y,R,B,T,S,T,T,T],
            [T,T,T,T,T,B,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,T,B,D,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,T,B,B,T,T,T,T,T,T],
            [T,T,T,O,D,O,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – sweat above
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,S,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,S,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- tired (droopy ears, slow tail) ---
    private static let normalTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – droop more
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,O,D,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – eyes closing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – tail low
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,T,O,D,O,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- collab (two foxes implied, high-five pose) ---
    private static let normalCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – paw reaching right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – high five!
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,B,Y,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – paw back
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – settle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,W,W,W,O,D,B,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ──────────────────────────────────────────────
    // MARK: - Buff  (broader shoulders, fluffier tail)
    // ──────────────────────────────────────────────

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return buffIdle
        case .normal:   return buffWalk
        case .busy:     return buffBusy
        case .bloated:  return buffBloated
        case .stressed: return buffStressed
        case .tired:    return buffTired
        case .collab:   return buffCollab
        }
    }

    // --- buff idle ---
    private static let buffIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,W,W,W,W,W,W,W,W,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,D,O,O,D,D,O,B,T,T,T],
            [T,O,D,O,O,W,B,B,B,B,W,O,D,W,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,W,W,W,W,W,W,W,W,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,D,O,O,D,D,O,B,T,T,T],
            [T,O,D,O,O,W,B,B,B,B,W,O,D,W,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,W,W,W,W,W,W,W,W,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,D,O,O,D,D,O,B,T,T,T],
            [T,O,D,O,O,W,B,B,B,B,W,O,D,W,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,W,W,W,W,W,W,W,W,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,D,O,O,D,D,O,B,T,T,T],
            [T,O,D,O,W,O,B,B,B,B,O,W,D,W,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,W,W,W,W,W,W,W,W,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,O,D,D,O,O,D,D,O,B,T,T,T],
            [T,O,D,O,O,W,B,B,B,B,W,O,D,W,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
        ],
    ]

    // --- buff walk ---
    private static let buffWalk: [[[UInt32?]]] = [
        // Frame 1 – standing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,B,B,T,T,T,T,T,T,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,B,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,B,T,T,T,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- buff busy ---
    private static let buffBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,W,O,O,O,B,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – arms out typing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,B,B,O,O,O,O,O,O,O,O,B,B,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,B,T,T,T],
            [T,T,T,B,D,O,W,W,W,W,O,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,W,O,O,O,B,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – alternate arms
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,B,B,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,O,B,B,T],
            [T,T,T,B,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,W,O,O,O,B,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,T,B,B,T,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- buff bloated ---
    private static let buffBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,D,O,O,W,W,W,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [B,O,O,O,O,O,W,W,W,O,O,O,O,O,B,T],
            [B,D,D,O,O,O,W,W,W,O,O,O,D,D,B,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,D,O,O,W,W,W,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [B,O,O,O,O,O,W,W,W,O,O,O,O,O,B,T],
            [B,D,D,O,O,O,W,W,W,O,O,O,D,D,B,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,B,B,T,T,T,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,D,O,O,W,W,W,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,T,T,T,T,T,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- buff stressed ---
    private static let buffStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,S,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,S,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – shake
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,B,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,R,Y,Y,R,B,T,S,T,T,T],
            [T,T,T,T,T,B,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,T,B,D,D,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,T,B,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,O,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,S,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,S,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,T,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- buff tired ---
    private static let buffTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,T,O,D,O,O,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,B,B,T,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- buff collab ---
    private static let buffCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – paw out
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – high five
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,B,Y,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,B,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ──────────────────────────────────────────────
    // MARK: - Macho  (massive foxzilla, gold sparkles)
    // ──────────────────────────────────────────────

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return machoIdle
        case .normal:   return machoWalk
        case .busy:     return machoBusy
        case .bloated:  return machoBloated
        case .stressed: return machoStressed
        case .tired:    return machoTired
        case .collab:   return machoCollab
        }
    }

    // --- macho idle ---
    private static let machoIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,O,W,W,W,W,W,W,O,D,D,B,T],
            [B,D,D,W,W,W,W,W,W,W,W,W,W,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,O,B,T],
            [T,T,B,O,D,D,O,O,O,O,D,D,O,B,T,T],
            [O,D,O,O,O,W,B,B,B,B,W,O,O,O,D,W],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,O,W,W,W,W,W,W,O,D,D,B,T],
            [B,D,D,W,W,W,W,W,W,W,W,W,W,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,O,B,T],
            [T,T,B,O,D,D,O,O,O,O,D,D,O,B,T,T],
            [O,D,O,O,O,W,B,B,B,B,W,O,O,O,D,W],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,O,W,W,W,W,W,W,O,D,D,B,T],
            [B,D,D,W,W,W,W,W,W,W,W,W,W,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,O,B,T],
            [T,T,B,O,D,D,O,O,O,O,D,D,O,B,T,T],
            [O,D,O,O,O,W,B,B,B,B,W,O,O,O,D,W],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,O,W,W,W,W,W,W,O,D,D,B,T],
            [B,D,D,W,W,W,W,W,W,W,W,W,W,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,O,B,T],
            [T,T,B,O,D,D,O,O,O,O,D,D,O,B,T,T],
            [O,D,O,O,W,O,B,B,B,B,O,W,O,O,D,W],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,T,B,O,B,O,N,O,O,B,T,T,T,T],
            [T,T,T,B,D,O,O,W,W,O,O,D,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,B,D,D,O,W,W,W,W,W,W,O,D,D,B,T],
            [B,D,D,W,W,W,W,W,W,W,W,W,W,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,O,B,T],
            [T,T,B,O,D,D,O,O,O,O,D,D,O,B,T,T],
            [O,D,O,O,O,W,B,B,B,B,W,O,O,O,D,W],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- macho walk (massive, gold sparkle) ---
    private static let machoWalk: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,Y,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,Y,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,B,B,T,T,T,T,T,T,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,B,T,T,T,B,T,Y,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,B,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,B,T,T,T,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,Y,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,Y,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- macho busy ---
    private static let machoBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,Y,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,W,O,O,O,B,T,T],
            [T,B,D,D,D,O,W,W,W,W,O,D,D,D,B,T],
            [T,B,D,D,O,O,O,O,O,O,O,O,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,T,T,B,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – arms out
        [
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,Y,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,B,B,O,O,O,O,O,O,O,O,B,B,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,T,B,D,D,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,B,T,T,T,T,T,B,Y,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,W,O,O,O,B,T,T],
            [T,B,D,D,D,O,W,W,W,W,O,D,D,D,B,T],
            [T,B,D,D,O,O,O,O,O,O,O,O,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,T,T,B,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – alternate arms
        [
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,Y,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,B,B,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,O,O,W,W,W,W,O,O,O,B,B,T],
            [T,T,B,D,D,O,W,W,W,W,O,D,D,B,T,T],
            [T,T,B,D,D,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,B,T,T,T,T,T,B,T,Y,T,T,T],
            [T,T,T,T,B,O,B,T,T,B,O,B,T,T,T,T],
            [T,T,T,T,B,P,B,T,T,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,O,Y,O,B,T,T,T,T],
            [T,T,T,T,B,O,O,N,N,O,O,B,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,W,O,O,O,B,T,T],
            [T,B,D,D,D,O,W,W,W,W,O,D,D,D,B,T],
            [T,B,D,D,O,O,O,O,O,O,O,O,D,D,B,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,T,T,B,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,T,B,B,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- macho bloated ---
    private static let machoBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [B,D,D,D,O,O,W,W,W,O,O,D,D,D,B,T],
            [B,D,D,O,O,O,O,O,O,O,O,O,D,D,B,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,B,B,T,T,T,T,B,B,B,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – expand
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [B,O,O,O,O,O,W,W,W,O,O,O,O,O,B,T],
            [D,D,D,O,O,O,W,W,W,O,O,O,D,D,D,B],
            [D,D,O,O,O,O,O,O,O,O,O,O,O,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,B,B,T,T,T,T,B,B,B,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – breathe
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [B,D,D,D,O,O,W,W,W,O,O,D,D,D,B,T],
            [B,D,D,O,O,O,O,O,O,O,O,O,D,D,B,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,B,B,T,T,T,T,B,B,B,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – expand again
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [B,O,O,O,O,O,W,W,W,O,O,O,O,O,B,T],
            [D,D,D,O,O,O,W,W,W,O,O,O,D,D,D,B],
            [D,D,O,O,O,O,O,O,O,O,O,O,O,D,D,B],
            [T,B,O,O,O,O,O,O,O,O,O,O,O,B,T,T],
            [T,T,T,B,B,B,T,T,T,T,B,B,B,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – settle
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,B,O,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [B,D,D,D,O,O,W,W,W,O,O,D,D,D,B,T],
            [B,D,D,O,O,O,O,O,O,O,O,O,D,D,B,T],
            [T,B,O,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,B,B,T,T,T,T,T,B,B,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,T,B,B,T,T,T,T],
            [O,D,O,O,W,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- macho stressed ---
    private static let machoStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,S,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,S,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – shake
        [
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,B,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,B,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,R,Y,Y,R,B,T,S,T,T,T],
            [T,T,T,T,T,B,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,W,W,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,T,B,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,T,B,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,T,B,D,D,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,T,B,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,O,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,B,T,T,T,B,T,S,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,S,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,Y,O,Y,R,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,B,T,T,T,T,T,B,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- macho tired ---
    private static let machoTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,O,D,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [T,T,O,D,O,O,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,P,T,P,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,O,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- macho collab (massive, high five with sparkle) ---
    private static let machoCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,Y,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – arm reaching
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,Y,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – HIGH FIVE with sparkle
        [
            [T,T,T,T,T,B,T,T,T,B,T,Y,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,B,Y,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,Y,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,T,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,B,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,O,B,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,B,T,B,O,B,Y,T,T,T,T],
            [T,T,T,T,B,P,B,T,B,P,B,T,T,T,T,T],
            [T,T,T,T,T,B,O,O,O,B,T,T,T,T,T,T],
            [T,T,T,T,B,O,Y,O,Y,O,B,T,T,T,T,T],
            [T,T,T,T,B,O,O,N,O,O,B,T,T,T,T,T],
            [T,T,T,T,T,B,W,W,W,B,T,T,T,T,T,T],
            [T,T,T,B,O,O,O,O,O,O,O,B,T,T,T,T],
            [T,T,B,O,O,O,W,W,W,O,O,O,B,T,T,T],
            [T,B,D,D,D,O,W,W,W,O,D,D,D,B,T,T],
            [T,B,D,D,O,O,O,O,O,O,O,D,D,B,T,T],
            [T,T,B,O,O,O,O,O,O,O,O,O,B,T,T,T],
            [T,T,T,T,T,B,T,T,T,B,T,T,T,T,T,T],
            [T,T,T,T,B,B,T,T,T,B,B,T,T,T,T,T],
            [O,D,O,O,O,W,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]
}
