import Foundation

// MARK: - Color Aliases
private let W = CLR_WHITE    // Body (0xFFFFFFFF)
private let L = CLR_LGRAY    // Body shading (0xFFCCCCCC)
private let O = CLR_ORANGE   // Beak/feet (0xFFFF8C42)
private let B = CLR_BLACK    // Eyes (0xFF2D2D2D)
private let G = CLR_GRAY     // Wing shading (0xFFAAAAAA)
private let Y = CLR_GOLD     // Macho sparkle
private let S = CLR_SKYBLUE  // Sweat
private let R = CLR_RED      // Stress
private let Z = CLR_GRAY     // Zzz
private let T: UInt32? = nil

// MARK: - GooseSprites

struct GooseSprites: SpriteProvider {

    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    // ───────────────────────────────────────────────
    // MARK: - Normal muscle
    // ───────────────────────────────────────────────

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return normalIdle
        case .normal:   return normalNormal
        case .busy:     return normalBusy
        case .bloated:  return normalBloated
        case .stressed: return normalStressed
        case .tired:    return normalTired
        case .collab:   return normalCollab
        }
    }

    // -- Normal / Idle: sleeping goose, head tucked, Zzz floats --
    private static let normalIdle: [[[UInt32?]]] = [
        // Frame 1 – head tucked right, Zzz top-right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2 – same pose, Zzz shifted up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3 – head tilts slightly
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,B,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4 – Zzz bigger
        [
            [T,T,T,T,T,T,T,T,T,T,T,Z,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 5 – Zzz floats off
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Normal: tall goose walking, honk animation --
    private static let normalNormal: [[[UInt32?]]] = [
        // Frame 1 – standing tall, beak closed
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – walking step left foot forward
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – honk! beak open
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – walking step right foot forward
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – neck stretch forward (menacing)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,B,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Busy: goose typing/pecking furiously --
    private static let normalBusy: [[[UInt32?]]] = [
        // Frame 1 – neck down, pecking
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – head down lower, beak hitting
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – head pops back up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – head down pecking again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,B,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 5 – wing flap while pecking
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Bloated: fat goose, puffed body, waddling --
    private static let normalBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2 – waddle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,T,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – center again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4 – waddle right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,B,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,W,W,T,T,T],
            [T,T,T,T,T,G,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,T,T,G,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,O,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – burp/honk
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
        ],
    ]

    // -- Normal / Stressed: panicking goose with sweat/exclamation --
    private static let normalStressed: [[[UInt32?]]] = [
        // Frame 1 – sweat drops
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,S,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – honking in stress, exclamation
        [
            [T,T,T,T,T,T,T,T,T,T,T,R,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,R,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – flapping wings in panic
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,S,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,G,G,G,W,W,W,G,G,G,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – shaking, sweat right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,S,T,T,T],
            [T,T,T,T,T,T,T,W,B,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,G,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,G,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,O,O,T,T,T,T,T],
        ],
        // Frame 5 – angry honk, exclamation
        [
            [T,T,T,T,T,T,T,T,T,T,R,T,R,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,R,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Tired: droopy goose, slow movement --
    private static let normalTired: [[[UInt32?]]] = [
        // Frame 1 – droopy neck
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – eyes half closed (B → L for drowsy)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,L,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – yawn, beak open
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,L,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – drooping more
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,L,W,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 5 – small sigh, back to droopy
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Collab: goose with friend, wing wave --
    private static let normalCollab: [[[UInt32?]]] = [
        // Frame 1 – wing up wave
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – wing higher
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – both wings out (celebrating)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,T,W,T,G,T,T,T,T,T,T],
            [T,T,T,T,G,T,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – wing down right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 5 – happy honk
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // ───────────────────────────────────────────────
    // MARK: - Buff muscle
    // ───────────────────────────────────────────────

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return buffIdle
        case .normal:   return buffNormal
        case .busy:     return buffBusy
        case .bloated:  return buffBloated
        case .stressed: return buffStressed
        case .tired:    return buffTired
        case .collab:   return buffCollab
        }
    }

    // -- Buff / Idle: thick-necked goose sleeping --
    private static let buffIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,B,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,Z,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Normal: intimidating goose, thick neck, strutting --
    private static let buffNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2 – left step
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – honk
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4 – right step
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – chest puff, menacing lean
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Busy --
    private static let buffBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2 – head down
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3 – head back up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4 – pecking with wing flap
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,G,W,W,W,G,G,G,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Bloated --
    private static let buffBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        ],
        // Frame 2 – waddle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,W,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,G,G,W,W,W,W,W,G,G,T,T,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3 – center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        ],
        // Frame 4 – waddle right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,W,W,T,T,T],
            [T,T,T,T,G,G,W,W,W,W,W,G,G,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – honk
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,T,O,T,T,T,T,T],
        ],
    ]

    // -- Buff / Stressed --
    private static let buffStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,S,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2 – honk stress
        [
            [T,T,T,T,T,T,T,T,T,T,R,T,R,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,R,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3 – wing flap panic
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,S,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,G,W,W,W,G,G,G,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4 – shake right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,S,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,B,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,G,G,W,W,W,G,G,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,T,O,T,T,T,T,T],
        ],
        // Frame 5 – angry honk
        [
            [T,T,T,T,T,T,T,T,T,T,R,R,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,R,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,O,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Tired --
    private static let buffTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,L,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2 – eyes half closed
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,L,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3 – yawn
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,L,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4 – drooping lower
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,L,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 5 – back to droopy
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Collab --
    private static let buffCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 2 – wing higher
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 3 – both wings out
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,T,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,G,T,T,W,W,W,T,T,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 4 – wing down left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,G,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
        // Frame 5 – happy honk
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,G,G,T,T,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,T,O,T,T,T,T,T,T],
        ],
    ]

    // ───────────────────────────────────────────────
    // MARK: - Macho muscle
    // ───────────────────────────────────────────────

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return machoIdle
        case .normal:   return machoNormal
        case .busy:     return machoBusy
        case .bloated:  return machoBloated
        case .stressed: return machoStressed
        case .tired:    return machoTired
        case .collab:   return machoCollab
        }
    }

    // -- Macho / Idle: absolute unit goose sleeping, sparkles --
    private static let machoIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 3 – sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,B,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,Y,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,Z,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,Z,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,Y,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
    ]

    // -- Macho / Normal: absolute unit strutting, sparkles, tree trunk neck --
    private static let machoNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2 – step left, sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,Y,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,O,O,T,T,T,T,T],
        ],
        // Frame 3 – honk, flex
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,Y,T,W,W,W,W,W,W,T,Y,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,G,G,W,W,W,W,W,W,W,G,G,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4 – step right, sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,Y,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – power pose, arms wide
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,Y,T,W,W,W,W,W,W,T,T,Y,T,T,T],
            [T,T,G,G,G,W,W,W,W,W,G,G,G,T,T,T],
            [T,G,G,G,W,W,W,W,W,W,W,G,G,G,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
    ]

    // -- Macho / Busy: furious pecking, massive goose --
    private static let machoBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2 – head down peck
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 3 – head back up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4 – peck with arm flex
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,Y,T,W,W,W,W,W,W,T,Y,T,T,T,T],
            [T,T,G,G,G,W,W,W,W,W,G,G,G,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
    ]

    // -- Macho / Bloated: massive round goose --
    private static let machoBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,W,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,G,G,W,W,W,W,W,W,W,G,G,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
        ],
        // Frame 2 – waddle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,W,B,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,W,W,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,W,W,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,G,G,W,W,W,W,W,W,W,G,G,T,T,T,T],
            [T,G,W,W,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,G,W,W,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,W,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,W,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,G,G,W,W,W,W,W,W,W,G,G,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
        ],
        // Frame 4 – waddle right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,W,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,W,W,G,G,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,W,W,G,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,W,W,G,T,T],
            [T,T,T,T,W,W,W,W,W,W,W,W,W,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – honk
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,W,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,G,G,W,W,W,W,W,W,W,G,G,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,G,W,W,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,W,W,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
        ],
    ]

    // -- Macho / Stressed: massive panicking goose --
    private static let machoStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,S,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2 – honk stress, exclamation
        [
            [T,T,T,T,T,T,T,T,T,T,R,T,R,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,R,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,O,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 3 – arm flap panic
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,S,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,G,G,G,W,W,W,W,W,G,G,G,T,T,T],
            [T,G,G,G,W,W,W,W,W,W,W,G,G,G,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4 – shake
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,S,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,W,B,W,W,W,O,O,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,G,G,W,W,W,W,W,G,G,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,T,G,W,W,W,W,W,W,W,G,T,T,T],
            [T,T,T,T,T,T,W,W,W,W,W,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,W,T,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,T,O,O,T,T,T,T],
        ],
        // Frame 5 – angry honk with sparkle rage
        [
            [T,T,T,T,T,T,T,T,T,T,R,T,R,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,R,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,O,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,Y,T,T,W,W,W,W,T,T,Y,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
    ]

    // -- Macho / Tired: massive droopy goose --
    private static let machoTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,L,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2 – drooping
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,W,L,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 3 – yawn
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,L,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4 – drooping further
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,T,T,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,W,L,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,W,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 5 – sigh
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
    ]

    // -- Macho / Collab: absolute unit goose celebrating with sparkles --
    private static let machoCollab: [[[UInt32?]]] = [
        // Frame 1 – arm up right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,T,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 2 – arm higher + sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,G,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,Y,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,T,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 3 – both arms out, sparkles
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,Y,T,T,W,W,W,W,T,T,Y,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,G,G,G,W,W,W,W,W,G,G,G,T,T,T],
            [T,G,G,G,W,W,W,W,W,W,W,G,G,G,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 4 – arm down left + sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,G,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,Y,G,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
        // Frame 5 – happy honk + sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,W,B,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,W,W,W,W,W,W,T,Y,T,T,T,T],
            [T,T,T,G,G,W,W,W,W,W,G,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,G,W,W,W,W,W,W,W,G,T,T,T,T],
            [T,T,T,T,T,W,W,W,W,W,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,W,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,W,T,W,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,O,O,T,T,T,T,T],
        ],
    ]
}
