import Foundation

// MARK: - Color Aliases
private let M: UInt32? = CLR_BROWN    // Main body
private let N: UInt32? = CLR_DBROWN   // Body shading
private let E: UInt32? = CLR_BEIGE    // Belly/cheeks
private let F: UInt32? = CLR_DBEIGE   // Belly shading
private let B: UInt32? = CLR_BLACK    // Eyes
private let P: UInt32? = CLR_PINK     // Nose
private let K: UInt32? = CLR_BLUSH    // Inner ears
private let O: UInt32? = CLR_DBROWN   // Outline
private let Y: UInt32? = CLR_GOLD     // Macho sparkle
private let W: UInt32? = CLR_WHITE    // Whites / highlights
private let G: UInt32? = CLR_GRAY     // Sweat
private let L: UInt32? = CLR_SKYBLUE  // Sweat drop
private let T: UInt32? = nil          // Transparent

// MARK: - HamsterSprites

struct HamsterSprites: SpriteProvider {

    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    // =========================================================================
    // MARK: - Normal Muscle
    // =========================================================================

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return normalIdle
        case .normal:   return normalWalk
        case .busy:     return normalBusy
        case .bloated:  return normalBloated
        case .stressed: return normalStressed
        case .tired:    return normalTired
        case .collab:   return normalCollab
        }
    }

    // MARK: Normal / Idle — curled ball, breathing
    private static let normalIdle: [[[UInt32?]]] = [
        // Frame 1 – curled ball
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,M,N,O,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – slight expand (breathing in)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,M,N,O,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – same as frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,M,N,O,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – slight expand again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,M,N,O,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – tiny "zzz" bubble
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,W,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,W,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,M,N,O,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Normal / Walk — wobble side to side
    private static let normalWalk: [[[UInt32?]]] = [
        // Frame 1 – standing center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – wobble left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,O,M,K,O,O,K,M,O,T,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,O,T,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,O,E,B,E,M,M,E,B,E,O,T,T,T,T],
            [T,T,O,E,E,E,P,P,E,E,E,O,T,T,T,T],
            [T,O,M,E,E,E,E,E,E,E,E,M,O,T,T,T],
            [T,O,M,M,E,E,E,E,E,E,M,M,O,T,T,T],
            [T,O,M,M,M,E,E,E,E,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,N,O,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,T,T,M,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – standing center (same as 1)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – wobble right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,T,T,O,O,T,T,T],
            [T,T,T,T,T,T,O,M,K,O,O,K,M,O,T,T],
            [T,T,T,T,T,T,O,M,M,M,M,M,M,O,T,T],
            [T,T,T,T,T,O,M,M,M,M,M,M,M,M,O,T],
            [T,T,T,T,T,O,E,B,E,M,M,E,B,E,O,T],
            [T,T,T,T,T,O,E,E,E,P,P,E,E,E,O,T],
            [T,T,T,T,O,M,E,E,E,E,E,E,E,E,M,O],
            [T,T,T,T,O,M,M,E,E,E,E,E,E,M,M,O],
            [T,T,T,T,O,M,M,M,E,E,E,E,M,M,M,O],
            [T,T,T,T,T,O,M,M,M,M,M,M,M,M,O,T],
            [T,T,T,T,T,O,N,M,M,M,M,M,M,N,O,T],
            [T,T,T,T,T,T,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,T,T,O,M,T,T,M,O,T,T,T],
            [T,T,T,T,T,T,T,O,O,T,T,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – standing center variant (ears wiggle)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Normal / Busy — running wheel motion
    private static let normalBusy: [[[UInt32?]]] = [
        // Frame 1 – running pose A (left foot forward)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,T,T,T,T,M,O,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,T,T,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – running pose B (right foot forward)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,M,O,T,T,O,M,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – mid run (both feet tucked)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,O,M,M,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – running pose A again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,T,T,T,T,M,O,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,T,T,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – running pose B again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,M,O,T,T,O,M,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Normal / Bloated — puffed cheeks
    private static let normalBloated: [[[UInt32?]]] = [
        // Frame 1 – puffed cheeks big
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,E,E,B,E,M,M,M,E,B,E,E,E,O,T],
            [T,O,E,E,E,E,P,P,P,E,E,E,E,E,O,T],
            [T,O,E,E,E,E,E,E,E,E,E,E,E,E,O,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – cheeks pulse slightly bigger
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,E,E,E,E,E,E,E,E,E,E,E,E,E,E,O],
            [T,O,M,M,E,E,E,E,E,E,E,E,M,M,O,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – back to normal puff
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,E,E,B,E,M,M,M,E,B,E,E,E,O,T],
            [T,O,E,E,E,E,P,P,P,E,E,E,E,E,O,T],
            [T,O,E,E,E,E,E,E,E,E,E,E,E,E,O,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – cheeks pulse bigger again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,E,E,E,E,E,E,E,E,E,E,E,E,E,E,O],
            [T,O,M,M,E,E,E,E,E,E,E,E,M,M,O,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – looking uncomfortable
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,E,E,N,E,M,M,M,E,N,E,E,E,O,T],
            [T,O,E,E,E,E,P,P,P,E,E,E,E,E,O,T],
            [T,O,E,E,E,E,E,F,E,E,E,E,E,E,O,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Normal / Stressed — sweat drops
    private static let normalStressed: [[[UInt32?]]] = [
        // Frame 1 – sweat on right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,L,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,L,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,F,F,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – sweat drop falls
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,L,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,L,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,F,F,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – worried eyes, sweat left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,L,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,L,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,F,F,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – sweat drop falls left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,L,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,L,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,F,F,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – both sides sweat
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,L,T,T,O,O,T,T,O,O,T,T,L,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,F,F,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Normal / Tired — droopy
    private static let normalTired: [[[UInt32?]]] = [
        // Frame 1 – droopy eyes
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,N,N,M,M,N,N,M,O,T,T,T],
            [T,T,T,O,E,E,B,M,M,B,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,P,P,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,N,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – eyes closing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,N,N,M,M,N,N,M,O,T,T,T],
            [T,T,T,O,E,N,N,M,M,N,N,E,O,T,T,T],
            [T,T,O,M,E,E,E,P,P,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,N,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – eyes closed (sleeping line)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,N,N,M,M,N,N,E,O,T,T,T],
            [T,T,O,M,E,E,E,P,P,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,N,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – same as 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,N,N,M,M,N,N,M,O,T,T,T],
            [T,T,T,O,E,N,N,M,M,N,N,E,O,T,T,T],
            [T,T,O,M,E,E,E,P,P,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,N,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – droopy with zzz
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,W,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,W,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,N,N,M,M,N,N,E,O,T,T,T],
            [T,T,O,M,E,E,E,P,P,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,N,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Normal / Collab — waving
    private static let normalCollab: [[[UInt32?]]] = [
        // Frame 1 – right paw up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,M,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – right paw higher
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,M,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,M,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – right paw up (same as 1)
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,M,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – right paw higher again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,O,T,M,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,M,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – both paws waving
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,O,M,K,O,O,K,M,O,T,T,T,T],
            [T,T,M,T,O,M,M,M,M,M,M,O,T,M,T,T],
            [T,T,M,O,M,M,M,M,M,M,M,M,O,M,T,T],
            [T,T,T,O,E,B,E,M,M,E,B,E,O,T,T,T],
            [T,T,T,O,E,E,E,P,P,E,E,E,O,T,T,T],
            [T,T,O,M,E,E,E,E,E,E,E,E,M,O,T,T],
            [T,T,O,M,M,E,E,E,E,E,E,M,M,O,T,T],
            [T,T,O,M,M,M,E,E,E,E,M,M,M,O,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,T,O,N,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,O,M,T,T,M,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // =========================================================================
    // MARK: - Buff Muscle
    // =========================================================================

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return buffIdle
        case .normal:   return buffWalk
        case .busy:     return buffBusy
        case .bloated:  return buffBloated
        case .stressed: return buffStressed
        case .tired:    return buffTired
        case .collab:   return buffCollab
        }
    }

    // MARK: Buff / Idle — curled ball, broader
    private static let buffIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,N,M,M,M,M,M,M,N,M,O,T,T],
            [T,T,O,M,N,M,M,M,M,M,M,N,M,O,T,T],
            [T,O,M,M,E,E,E,E,E,E,E,E,M,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – breathing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,M,M,N,M,M,M,M,M,M,N,M,M,O,T],
            [T,O,M,M,N,M,M,M,M,M,M,N,M,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,N,M,M,M,M,M,M,N,M,O,T,T],
            [T,T,O,M,N,M,M,M,M,M,M,N,M,O,T,T],
            [T,O,M,M,E,E,E,E,E,E,E,E,M,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,M,M,N,M,M,M,M,M,M,N,M,M,O,T],
            [T,O,M,M,N,M,M,M,M,M,M,N,M,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – zzz
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,W,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,W,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,N,M,M,M,M,M,M,N,M,O,T,T],
            [T,T,O,M,N,M,M,M,M,M,M,N,M,O,T,T],
            [T,O,M,M,E,E,E,E,E,E,E,E,M,M,O,T],
            [T,O,M,E,E,E,E,E,E,E,E,E,E,M,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Buff / Walk — broader shoulders wobble
    private static let buffWalk: [[[UInt32?]]] = [
        // Frame 1 – standing center, buff arms
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – wobble left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
            [T,T,T,O,K,O,T,T,O,K,O,T,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,O,T,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,O,E,B,E,M,M,M,E,B,E,M,O,T,T,T],
            [T,O,E,E,E,P,P,P,E,E,E,M,O,T,T,T],
            [O,N,E,E,E,E,E,E,E,E,E,N,M,O,T,T],
            [O,N,M,E,E,E,E,E,E,E,M,N,M,O,T,T],
            [O,M,M,M,E,E,E,E,E,M,M,M,O,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,O,T,T,T,T],
            [T,O,N,M,M,M,M,M,M,M,N,O,T,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,O,M,M,T,T,M,M,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – wobble right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,T,T,T,O,O,T,T],
            [T,T,T,T,T,T,O,K,O,T,T,O,K,O,T,T],
            [T,T,T,T,T,O,M,M,M,M,M,M,M,M,O,T],
            [T,T,T,T,O,M,M,M,M,M,M,M,M,M,M,O],
            [T,T,T,T,O,E,B,E,M,M,M,E,B,E,M,O],
            [T,T,T,T,O,E,E,E,P,P,P,E,E,E,M,O],
            [T,T,T,O,N,E,E,E,E,E,E,E,E,E,N,O],
            [T,T,T,O,N,M,E,E,E,E,E,E,E,M,N,O],
            [T,T,T,T,O,M,M,E,E,E,E,E,M,M,O,T],
            [T,T,T,T,T,O,M,M,M,M,M,M,M,O,T,T],
            [T,T,T,T,T,O,N,M,M,M,M,M,N,O,T,T],
            [T,T,T,T,T,T,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,O,M,M,O,M,M,O,T,T],
            [T,T,T,T,T,T,T,O,O,O,T,O,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – center, ears wiggle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,T,T,O,O,T,T,T],
            [T,T,T,O,K,O,T,T,T,T,O,K,O,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Buff / Busy — fast running, muscled
    private static let buffBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,T,T,T,T,M,M,O,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,T,T,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,M,M,O,O,M,M,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,O,M,M,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,M,M,T,T,T,T,M,M,O,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,T,T,O,O,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,M,M,O,O,M,M,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Buff / Bloated — bigger cheeks, buff body
    private static let buffBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,O,T,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – pulse bigger
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [O,N,M,M,E,E,E,E,E,E,E,M,M,N,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – same as 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,O,T,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – pulse bigger
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [O,N,M,M,E,E,E,E,E,E,E,M,M,N,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – uncomfortable
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,M,O,T],
            [O,E,E,E,N,E,M,M,M,E,N,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,F,E,E,E,E,E,E,N,O],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,O,T,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Buff / Stressed — sweat, buff body
    private static let buffStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,L,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,L,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,F,F,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,L],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,L],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,F,F,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,L,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,L,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,F,F,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,L,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,L,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,F,F,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,L,T,O,O,T,T,T,T,O,O,T,L,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,F,F,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Buff / Tired
    private static let buffTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,N,N,M,M,M,N,N,M,M,O,T,T],
            [T,T,O,E,E,B,M,M,M,B,E,E,M,O,T,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,N,M,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,N,N,M,M,M,N,N,M,M,O,T,T],
            [T,T,O,E,N,N,M,M,M,N,N,E,M,O,T,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,N,M,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – closed eyes
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,N,N,M,M,M,N,N,E,M,O,T,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,N,M,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,N,N,M,M,M,N,N,M,M,O,T,T],
            [T,T,O,E,N,N,M,M,M,N,N,E,M,O,T,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,N,M,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – zzz
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,W,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,N,N,M,M,M,N,N,E,M,O,T,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,N,M,M,M,M,M,N,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Buff / Collab — waving with buff arms
    private static let buffCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,N,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,O,N,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,N,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,N,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,N,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,O,N,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,N,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,N,T],
            [T,T,T,O,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – both arms wave
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,N,T,O,M,M,M,M,M,M,M,M,O,T,N,T],
            [T,N,O,M,M,M,M,M,M,M,M,M,M,O,N,T],
            [T,T,O,E,B,E,M,M,M,E,B,E,M,O,T,T],
            [T,T,O,E,E,E,P,P,P,E,E,E,M,O,T,T],
            [T,O,N,E,E,E,E,E,E,E,E,E,N,M,O,T],
            [T,O,N,M,E,E,E,E,E,E,E,M,N,M,O,T],
            [T,O,M,M,M,E,E,E,E,E,M,M,M,O,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [T,T,O,N,M,M,M,M,M,M,M,N,O,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,T,O,M,M,T,T,M,M,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // =========================================================================
    // MARK: - Macho Muscle
    // =========================================================================

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return machoIdle
        case .normal:   return machoWalk
        case .busy:     return machoBusy
        case .bloated:  return machoBloated
        case .stressed: return machoStressed
        case .tired:    return machoTired
        case .collab:   return machoCollab
        }
    }

    // MARK: Macho / Idle — muscled ball with sparkles
    private static let machoIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [O,M,N,E,E,E,E,E,E,E,E,E,E,N,M,O],
            [O,M,E,E,E,E,E,E,E,E,E,E,E,E,M,O],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [T,O,O,O,O,O,O,O,O,O,O,O,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Y,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [O,M,N,E,E,E,E,E,E,E,E,E,E,N,M,O],
            [O,M,E,E,E,E,E,E,E,E,E,E,E,E,M,O],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [T,O,O,O,O,O,O,O,O,O,O,O,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [O,M,N,E,E,E,E,E,E,E,E,E,E,N,M,O],
            [O,M,E,E,E,E,E,E,E,E,E,E,E,E,M,O],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [T,O,O,O,O,O,O,O,O,O,O,O,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – sparkle other side
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,Y,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [O,M,N,E,E,E,E,E,E,E,E,E,E,N,M,O],
            [O,M,E,E,E,E,E,E,E,E,E,E,E,E,M,O],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [T,O,O,O,O,O,O,O,O,O,O,O,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – zzz + sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,W,T,Y,T],
            [T,T,T,T,T,T,T,T,T,T,T,W,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,N,M,M,M,M,M,M,M,M,N,N,O,T],
            [O,M,N,E,E,E,E,E,E,E,E,E,E,N,M,O],
            [O,M,E,E,E,E,E,E,E,E,E,E,E,E,M,O],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [T,O,O,O,O,O,O,O,O,O,O,O,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Macho / Walk — huge muscles, sparkle walk
    private static let machoWalk: [[[UInt32?]]] = [
        // Frame 1 – center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – wobble left, sparkle right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,O,O,T,T,T,Y,T],
            [T,T,T,O,K,O,T,T,O,K,O,T,T,T,T,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [O,N,M,M,M,M,M,M,M,M,M,M,N,O,T,T],
            [O,N,E,B,E,M,M,M,E,B,E,N,N,O,T,T],
            [O,N,E,E,E,P,P,P,E,E,E,N,N,O,T,T],
            [N,N,E,E,E,E,E,E,E,E,E,E,N,N,O,T],
            [N,N,M,E,E,E,E,E,E,E,M,N,N,N,O,T],
            [N,M,M,M,E,E,E,E,E,M,M,M,N,O,T,T],
            [O,M,M,M,M,M,M,M,M,M,M,M,O,T,T,T],
            [O,N,N,M,M,M,M,M,M,M,N,N,O,T,T,T],
            [T,O,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,O,M,M,M,T,T,M,M,M,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – center, sparkle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,Y,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – wobble right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,T,T,T,O,O,T,T],
            [T,T,T,T,T,T,O,K,O,T,T,O,K,O,T,T],
            [T,T,T,T,O,M,M,M,M,M,M,M,M,M,M,O],
            [T,T,T,O,N,M,M,M,M,M,M,M,M,M,N,O],
            [T,T,T,O,N,E,B,E,M,M,M,E,B,E,N,O],
            [T,T,T,O,N,E,E,E,P,P,P,E,E,E,N,O],
            [T,T,O,N,N,E,E,E,E,E,E,E,E,E,N,N],
            [T,T,O,N,N,M,E,E,E,E,E,E,E,M,N,N],
            [T,T,T,O,N,M,M,E,E,E,E,E,M,M,N,O],
            [T,T,T,T,O,M,M,M,M,M,M,M,M,M,O,T],
            [T,T,T,T,O,N,N,M,M,M,M,M,N,N,O,T],
            [T,T,T,T,T,O,O,O,O,O,O,O,O,O,T,T],
            [T,T,T,T,T,O,M,M,M,T,T,M,M,M,O,T],
            [T,T,T,T,T,O,O,O,O,T,T,O,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – center, double sparkle
        [
            [T,T,Y,T,T,T,T,T,T,T,T,T,T,Y,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Macho / Busy — power running
    private static let machoBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,T,T,T,T,T,T,M,M,O,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,T,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,Y,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,M,M,O,O,O,M,M,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,Y,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,T,O,M,M,M,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,Y,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,O,M,M,T,T,T,T,T,T,M,M,O,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,T,O,O,O,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,Y,T,T,O,O,T,T,T,T,O,O,T,T,Y,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,T,M,M,O,O,O,M,M,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Macho / Bloated — massive cheeks, still muscled
    private static let machoBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – pulse bigger
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,Y,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – pulse bigger, sparkle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,Y,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [O,E,E,E,B,E,M,M,M,E,B,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,E,E,E,E,E,E,E,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – uncomfortable face
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [O,N,N,M,M,M,M,M,M,M,M,M,M,N,N,O],
            [O,E,E,E,N,E,M,M,M,E,N,E,E,E,E,O],
            [O,E,E,E,E,E,P,P,P,E,E,E,E,E,E,O],
            [O,N,E,E,E,E,E,F,E,E,E,E,E,E,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Macho / Stressed — sweat, muscles, sparkles
    private static let machoStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,L,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,L,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,F,F,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,L],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,L],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,F,F,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,L,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,L,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,F,F,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [L,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [L,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,F,F,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – both sides sweat
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,L,T,T,O,O,T,T,T,T,O,O,T,T,L,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,F,F,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Macho / Tired
    private static let machoTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,M,N,N,M,M,M,N,N,M,N,N,O,T],
            [T,O,N,E,E,B,M,M,M,B,E,E,N,N,O,T],
            [O,N,N,E,E,E,P,P,P,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,N,M,M,M,M,M,N,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,M,N,N,M,M,M,N,N,M,N,N,O,T],
            [T,O,N,E,N,N,M,M,M,N,N,E,N,N,O,T],
            [O,N,N,E,E,E,P,P,P,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,N,M,M,M,M,M,N,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3 – closed eyes
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,E,N,N,M,M,M,N,N,E,N,N,O,T],
            [O,N,N,E,E,E,P,P,P,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,N,M,M,M,M,M,N,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,M,N,N,M,M,M,N,N,M,N,N,O,T],
            [T,O,N,E,N,N,M,M,M,N,N,E,N,N,O,T],
            [O,N,N,E,E,E,P,P,P,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,N,M,M,M,M,M,N,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – zzz
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,W,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,N,N,O,T],
            [T,O,N,E,N,N,M,M,M,N,N,E,N,N,O,T],
            [O,N,N,E,E,E,P,P,P,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,N,M,M,M,M,M,N,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // MARK: Macho / Collab — power waving with sparkles
    private static let machoCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,N],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,O,N],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2 – arm up, sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,Y,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,N,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,N],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,N],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,O,N],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4 – arm highest, sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,N,T,T],
            [T,Y,T,T,O,K,O,T,T,O,K,O,T,N,T,T],
            [T,T,O,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,M,M,M,M,M,M,M,M,M,M,N,O,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5 – both arms wave, double sparkle
        [
            [T,T,Y,T,T,T,T,T,T,T,T,T,T,T,Y,T],
            [T,T,T,T,O,O,T,T,T,T,O,O,T,T,T,T],
            [T,T,T,T,O,K,O,T,T,O,K,O,T,T,T,T],
            [T,N,O,M,M,M,M,M,M,M,M,M,M,O,N,T],
            [T,N,N,M,M,M,M,M,M,M,M,M,M,N,N,T],
            [T,O,N,E,B,E,M,M,M,E,B,E,N,N,O,T],
            [T,O,N,E,E,E,P,P,P,E,E,E,N,N,O,T],
            [O,N,N,E,E,E,E,E,E,E,E,E,E,N,N,O],
            [O,N,N,M,E,E,E,E,E,E,E,M,N,N,N,O],
            [O,N,M,M,M,E,E,E,E,E,M,M,M,N,O,T],
            [T,O,M,M,M,M,M,M,M,M,M,M,M,O,T,T],
            [T,O,N,N,M,M,M,M,M,M,M,N,N,O,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,O,T,T,T],
            [T,T,T,O,M,M,M,T,T,M,M,M,O,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,O,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]
}
