import Foundation

// MARK: - Color Aliases

private let B: UInt32? = CLR_BLACK    // Body
private let G: UInt32? = CLR_DGRAY    // Body shading
private let W: UInt32? = CLR_WHITE    // Belly
private let L: UInt32? = CLR_LGRAY    // Belly shading
private let O: UInt32? = CLR_ORANGE   // Beak / feet
private let S: UInt32? = CLR_SKYBLUE  // Scarf accent
private let Y: UInt32? = CLR_GOLD     // Macho sparkle
private let P: UInt32? = CLR_PINK     // Blush
private let R: UInt32? = CLR_RED      // Stress
private let Z: UInt32? = CLR_GRAY     // Zzz
private let T: UInt32? = nil          // Transparent

// MARK: - PenguinSprites

struct PenguinSprites: SpriteProvider {

    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    // ──────────────────────────────────────────────
    // MARK: - Normal  (classic tuxedo penguin)
    // ──────────────────────────────────────────────

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return normalIdle
        case .normal:   return normalWalk
        case .busy:     return normalBusy
        case .bloated:  return normalBloated
        case .stressed: return normalStressed
        case .tired:    return normalTired
        case .collab:   return normalCollab
        }
    }

    // --- idle (sleeping penguin, gentle sway) ---
    private static let normalIdle: [[[UInt32?]]] = [
        // Frame 1 – standing asleep
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – Zzz appearing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – Zzz higher
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – Zzz fading, slight lean
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,G,B,B,G,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 5 – back to center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- normal (happy waddle) ---
    private static let normalWalk: [[[UInt32?]]] = [
        // Frame 1 – center stance
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – waddle right, flipper up left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,W,B,B,W,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,T,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,T,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,T,O,O,T,T,T,T],
        ],
        // Frame 3 – center, feet together
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – waddle left, flipper up right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,B,W,B,B,W,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,T,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,B,B,T,B,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,T,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 5 – center again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- busy (rapid typing motion with flippers) ---
    private static let normalBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,T,B,B,W,W,W,W,B,B,T,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – flippers down typing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – flippers out typing
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,B,T,B,B,W,W,W,W,W,W,B,B,T,B,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – flippers in
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,T,B,B,W,W,W,W,B,B,T,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- bloated (fat penguin, slow sway) ---
    private static let normalBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – sway right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,W,B,B,W,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,T,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,T,B,B,B,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3 – center puffed
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – sway left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,B,W,B,B,W,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,T,T,T,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,B,T,T,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,B,B,W,W,W,L,L,W,W,W,W,B,B,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,B,B,B,W,W,W,W,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
        ],
        // Frame 5 – center again
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- stressed (red accents, shaking) ---
    private static let normalStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,R,R,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – shake right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,R,B,B,R,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3 – stress marks
        [
            [T,T,T,T,T,T,T,T,T,T,T,R,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,R,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – shake left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,B,R,B,B,R,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,T,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,B,B,T,T,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,B,T,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
        ],
        // Frame 5 – center with marks
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,R,R,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- tired (droopy, slow waddle) ---
    private static let normalTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – droop right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,G,B,B,G,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,T,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3 – center sag
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – droop left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,B,G,B,B,G,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,T,T,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,B,B,T,T,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,B,T,T,T,T],
            [T,T,B,B,W,W,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
        ],
        // Frame 5 – back center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- collab (two penguins vibe, happy with blush) ---
    private static let normalCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – wave right flipper
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 3 – both flippers up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,T,B,B,W,W,W,W,B,B,T,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – wave left flipper
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,B,B,T,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5 – back to normal
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // ──────────────────────────────────────────────
    // MARK: - Buff  (broader chest, defined pecs)
    // ──────────────────────────────────────────────

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return buffIdle
        case .normal:   return buffWalk
        case .busy:     return buffBusy
        case .bloated:  return buffBloated
        case .stressed: return buffStressed
        case .tired:    return buffTired
        case .collab:   return buffCollab
        }
    }

    // --- buff idle ---
    private static let buffIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – lean
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,G,B,B,G,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,T,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,T,B,B,B,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- buff walk ---
    private static let buffWalk: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2 – waddle right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,W,B,B,W,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,T,T,B,W,W,L,L,W,W,B,B,T,T],
            [T,B,B,T,B,B,W,W,L,L,W,W,W,B,B,T],
            [T,T,T,T,B,B,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,T,T,B,B,B,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,T,O,O,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4 – waddle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,W,B,B,W,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,W,W,L,L,W,W,B,T,T,B,T,T],
            [T,B,B,W,W,W,L,L,W,W,W,B,B,B,B,T],
            [T,B,B,W,W,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,B,W,W,W,W,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- buff busy ---
    private static let buffBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,T,B,W,W,L,L,W,W,B,B,T,B,T],
            [T,T,T,B,B,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,T,B,B,W,W,L,L,W,W,B,B,T,B,T],
            [T,T,T,B,B,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,T,B,W,W,L,L,W,W,B,B,T,B,T],
            [T,T,T,B,B,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- buff bloated ---
    private static let buffBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,W,W,B,B,T],
            [T,B,B,W,W,W,W,L,L,W,W,W,W,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,W,B,B,W,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,B,B,W,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,T,B,B,B,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,W,W,B,B,T],
            [T,B,B,W,W,W,W,L,L,W,W,W,W,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,W,B,B,W,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,W,W,L,L,W,W,B,B,T,T,T,T],
            [T,B,B,W,W,W,L,L,W,W,W,B,B,T,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,B,B,W,W,W,L,L,W,W,W,W,B,B,T,T],
            [T,T,B,B,B,W,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,W,W,B,B,T],
            [T,B,B,W,W,W,W,L,L,W,W,W,W,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- buff stressed ---
    private static let buffStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,R,R,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,R,B,B,R,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,T,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,T,B,B,B,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,R,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,R,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,R,B,B,R,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,W,W,L,L,W,W,B,B,T,T,T,T],
            [T,B,B,W,W,W,L,L,W,W,W,B,B,T,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,B,W,W,W,W,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,R,R,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- buff tired ---
    private static let buffTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,G,B,B,G,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,T,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,T,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,B,B,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,G,B,B,G,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,W,W,L,L,W,W,B,B,T,T,T,T],
            [T,B,B,W,W,W,L,L,W,W,W,B,B,T,T,T],
            [T,B,B,W,W,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,B,B,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- buff collab ---
    private static let buffCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,B,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,T,B,W,W,L,L,W,W,B,B,T,B,T],
            [T,T,T,B,B,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,T,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,B,B,T,B,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,W,W,L,L,W,W,B,B,T,T,T],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,T,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
        ],
    ]

    // ──────────────────────────────────────────────
    // MARK: - Macho  (huge penguin, massive arms)
    // ──────────────────────────────────────────────

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return machoIdle
        case .normal:   return machoWalk
        case .busy:     return machoBusy
        case .bloated:  return machoBloated
        case .stressed: return machoStressed
        case .tired:    return machoTired
        case .collab:   return machoCollab
        }
    }

    // --- macho idle ---
    private static let machoIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – lean right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Z,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,G,B,B,G,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,B,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,B,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,B,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,O,O,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]

    // --- macho walk (massive arms waddle) ---
    private static let machoWalk: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2 – waddle right, left arm up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,W,B,B,W,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,B,T,B,B,W,W,L,L,W,W,B,B,B,T],
            [B,B,B,T,B,W,W,W,L,L,W,W,W,B,B,B],
            [T,B,T,B,B,W,W,W,W,W,W,W,W,B,B,B],
            [T,T,T,B,B,B,W,W,W,W,W,W,B,B,B,T],
            [T,T,T,T,B,B,B,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,T,T,O,O,T,T,T,T],
        ],
        // Frame 3 – center, feet together
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – waddle left, right arm up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,W,B,B,W,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,T,B,B,T],
            [T,B,B,B,W,W,W,L,L,W,W,B,T,B,B,B],
            [T,B,B,B,W,W,W,W,W,W,W,B,B,T,B,T],
            [T,T,B,B,B,W,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        ],
        // Frame 5 – center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]

    // --- macho busy (power typing with sparkles) ---
    private static let machoBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,B,T,B,W,W,L,L,W,W,B,B,T,B,B],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2 – arms down, sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [B,B,B,B,B,W,W,W,W,W,W,B,B,B,B,B],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3 – arms out
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,B,T,B,W,W,L,L,W,W,B,B,T,B,B],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – arms in, sparkle left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [B,B,B,B,B,W,W,W,W,W,W,B,B,B,B,B],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,B,T,B,W,W,L,L,W,W,B,B,T,B,B],
            [T,T,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,T,B,B,W,W,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,B,B,W,W,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]

    // --- macho bloated ---
    private static let machoBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [B,B,B,W,W,W,W,W,W,W,W,W,W,B,B,B],
            [B,B,B,W,W,W,W,L,L,W,W,W,W,B,B,B],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,B,W,W,W,W,B,B,B,B,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2 – sway
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,W,B,B,W,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,B,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,W,B,B,B],
            [T,B,B,B,W,W,W,W,L,L,W,W,W,B,B,B],
            [T,T,B,B,B,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,T,B,B,B,B,W,W,W,W,B,B,B,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,O,O,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [B,B,B,W,W,W,W,W,W,W,W,W,W,B,B,B],
            [B,B,B,W,W,W,W,L,L,W,W,W,W,B,B,B],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,B,W,W,W,W,B,B,B,B,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – sway left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,W,B,B,W,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,B,B,B,T,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,B,B,B,T,T],
            [B,B,B,W,W,W,W,W,W,W,W,W,B,B,B,T],
            [B,B,B,W,W,W,L,L,W,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,B,B,B,W,W,W,W,B,B,B,B,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [B,B,B,W,W,W,W,W,W,W,W,W,W,B,B,B],
            [B,B,B,W,W,W,W,L,L,W,W,W,W,B,B,B],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,B,W,W,W,W,B,B,B,B,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]

    // --- macho stressed ---
    private static let machoStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,R,R,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2 – shake right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,R,B,B,R,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,B,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,B,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,B,B,B,W,W,W,W,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,O,O,T,T,T,T],
        ],
        // Frame 3 – stress marks
        [
            [T,T,T,T,T,T,T,T,T,T,T,R,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,R,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – shake left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,R,B,B,R,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,B,B,B,T,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,R,R,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,R,B,B,R,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]

    // --- macho tired ---
    private static let machoTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2 – droop right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,G,B,B,G,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,O,O,B,B,B,T,T,T],
            [T,T,T,T,T,T,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,T,B,B,B,W,W,L,L,W,W,B,B,T,T],
            [T,T,B,B,B,W,W,W,L,L,W,W,W,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,W,W,B,B,T],
            [T,T,T,B,B,B,W,W,W,W,W,W,B,B,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,T,O,T,T,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,O,O,T,T,T,T],
        ],
        // Frame 3 – center with Z
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – droop left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,B,B,G,B,B,G,B,B,T,T,T,T,T],
            [T,T,T,B,B,B,O,O,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,T,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,T,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,B,B,B,T,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,G,B,B,G,B,B,T,T,T,T],
            [T,T,T,T,B,B,B,O,O,B,B,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,B,B,B,B,B,B,B,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]

    // --- macho collab (flex + sparkle) ---
    private static let machoCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 2 – flex right, sparkle
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,Y,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,B,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,B],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 3 – both arms flex, double sparkle
        [
            [T,Y,T,T,T,T,T,T,T,T,T,T,T,T,Y,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,B,B,B,W,W,L,L,W,W,B,B,B,B,T],
            [B,B,B,B,W,W,W,L,L,W,W,W,B,B,B,B],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 4 – flex left, sparkle
        [
            [T,Y,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,B,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [B,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,B,B,B,B,B,B,B,B,T,T,T,T],
            [T,T,T,T,B,B,W,B,B,W,B,B,T,T,T,T],
            [T,T,T,T,B,P,B,O,O,B,P,B,T,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,S,S,S,S,S,S,S,S,T,T,T,T],
            [T,T,B,B,B,W,W,L,L,W,W,B,B,B,T,T],
            [T,B,B,B,W,W,W,L,L,W,W,W,B,B,B,T],
            [T,B,B,B,W,W,W,W,W,W,W,W,B,B,B,T],
            [T,T,B,B,B,W,W,W,W,W,W,B,B,B,T,T],
            [T,T,T,B,B,B,W,W,W,W,B,B,B,T,T,T],
            [T,T,T,T,T,B,B,B,B,B,B,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,T,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
        ],
    ]
}
