import Foundation

// MARK: - Rabbit Sprite Color Aliases

private let W = CLR_WHITE    // Body (0xFFFFFFFF)
private let L = CLR_LGRAY    // Body shading (0xFFCCCCCC)
private let P = CLR_PINK     // Inner ears/nose (0xFFF5A0B8)
private let K = CLR_BLUSH    // Cheeks (0xFFFFB8C8)
private let B = CLR_BLACK    // Eyes (0xFF2D2D2D)
private let O = CLR_GRAY     // Outline (0xFFAAAAAA)
private let Y = CLR_GOLD     // Macho sparkle
private let S = CLR_SKYBLUE  // Sweat
private let R = CLR_RED      // Stress
private let Z = CLR_GRAY     // Zzz
private let T: UInt32? = nil

// MARK: - RabbitSprites

struct RabbitSprites: SpriteProvider {

    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch (state, muscle) {
        // ─── IDLE ───────────────────────────────────────────
        case (.idle, .normal):  return idleNormal
        case (.idle, .buff):    return idleBuff
        case (.idle, .macho):   return idleMacho
        // ─── NORMAL ─────────────────────────────────────────
        case (.normal, .normal):  return normalNormal
        case (.normal, .buff):    return normalBuff
        case (.normal, .macho):   return normalMacho
        // ─── BUSY ──────────────────────────────────────────
        case (.busy, .normal):  return busyNormal
        case (.busy, .buff):    return busyBuff
        case (.busy, .macho):   return busyMacho
        // ─── BLOATED ───────────────────────────────────────
        case (.bloated, .normal):  return bloatedNormal
        case (.bloated, .buff):    return bloatedBuff
        case (.bloated, .macho):   return bloatedMacho
        // ─── STRESSED ──────────────────────────────────────
        case (.stressed, .normal):  return stressedNormal
        case (.stressed, .buff):    return stressedBuff
        case (.stressed, .macho):   return stressedMacho
        // ─── TIRED ─────────────────────────────────────────
        case (.tired, .normal):  return tiredNormal
        case (.tired, .buff):    return tiredBuff
        case (.tired, .macho):   return tiredMacho
        // ─── COLLAB ────────────────────────────────────────
        case (.collab, .normal):  return collabNormal
        case (.collab, .buff):    return collabBuff
        case (.collab, .macho):   return collabMacho
        }
    }

    // ═══════════════════════════════════════════════════════
    // MARK: - IDLE (Sleeping bunny, ears drooped, Zzz)
    // ═══════════════════════════════════════════════════════

    // --- idle / normal ---
    private static let idleNormal: [[[UInt32?]]] = [
        // Frame 0: sleeping, ears drooped left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,B,W,B,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: sleeping, Zzz shift up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,B,W,B,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sleeping, Zzz at top
        [
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,B,W,B,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: sleeping, Zzz shift down
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,B,W,B,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sleeping, Zzz back to mid
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,O,O,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,B,W,B,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- idle / buff ---
    private static let idleBuff: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- idle / macho ---
    private static let idleMacho: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,Z,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,Z,T,Z,T,T,T],
            [O,P,P,W,W,O,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,B,W,W,W,B,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [T,O,W,K,W,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,O,W,W,W,T,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,W,O,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,B,W,W,W,B,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [T,O,W,K,W,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,O,W,W,W,T,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,W,O,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,B,W,W,W,B,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [T,O,W,K,W,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,O,W,W,W,T,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,Z,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,Z,T,Z,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,T,T,T,T,T,T],
            [O,P,P,W,W,O,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,B,W,W,W,B,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [T,O,W,K,W,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,O,W,W,W,T,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,T,T,T,T,T,T,T,Z,T,T,T,T],
            [O,P,P,W,O,T,T,T,T,T,Z,T,Z,T,T,T],
            [O,P,P,W,W,O,T,T,T,T,T,T,T,T,T,T],
            [T,O,O,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,B,W,W,W,B,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [T,O,W,K,W,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,O,W,W,W,T,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ═══════════════════════════════════════════════════════
    // MARK: - NORMAL (Hopping bunny, ears up)
    // ═══════════════════════════════════════════════════════

    // --- normal / normal ---
    private static let normalNormal: [[[UInt32?]]] = [
        // Frame 0: standing
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: hop up
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: hop peak
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: hop down
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: land
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- normal / buff ---
    private static let normalBuff: [[[UInt32?]]] = [
        // Frame 0: standing
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: hop up
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: hop peak
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: hop down
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: land
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- normal / macho ---
    private static let normalMacho: [[[UInt32?]]] = [
        // Frame 0: standing, sparkles
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,Y,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: hop up, sparkle shift
        [
            [T,Y,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: peak, sparkle opposite side
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,Y,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: descend
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,Y,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: land
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,Y,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ═══════════════════════════════════════════════════════
    // MARK: - BUSY (Fast tapping/typing motion)
    // ═══════════════════════════════════════════════════════

    // --- busy / normal ---
    private static let busyNormal: [[[UInt32?]]] = [
        // Frame 0: ears alert, paws moving left
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: paws right
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: ears twitch, paws left
        [
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: paws right
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: paws center
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- busy / buff ---
    private static let busyBuff: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,O,W,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,W,O,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,O,W,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,W,O,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- busy / macho ---
    private static let busyMacho: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [O,W,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,Y,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,W,O,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [O,W,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,Y,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,Y,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,W,O,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,Y,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ═══════════════════════════════════════════════════════
    // MARK: - BLOATED (Puffed up, round, slow)
    // ═══════════════════════════════════════════════════════

    // --- bloated / normal ---
    private static let bloatedNormal: [[[UInt32?]]] = [
        // Frame 0: puffed body
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,W,K,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: slight sway left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,T,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,P,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,O,W,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [T,O,K,W,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,T,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: puffed center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,W,K,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: sway right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,W,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,P,O,P,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,W,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,T,O,W,W,B,W,W,B,W,W,O,T,T,T],
            [T,T,T,O,W,W,W,W,P,W,W,W,O,T,T,T],
            [T,T,T,O,K,W,W,W,W,W,W,K,O,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,T,T,O,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,T,T,O,W,T,T,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: back to center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,W,K,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- bloated / buff ---
    private static let bloatedBuff: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,O,O,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,O,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,P,O,O,P,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [O,W,W,W,B,W,W,B,W,W,W,O,T,T,T,T],
            [O,W,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [O,W,K,W,W,W,W,W,W,K,W,O,T,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,O,W,W,T,T,W,W,O,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,O,P,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [T,T,O,W,W,W,B,W,W,B,W,W,W,O,T,T],
            [T,T,O,W,W,W,W,W,P,W,W,W,W,O,T,T],
            [T,T,O,W,K,W,W,W,W,W,W,K,W,O,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,T,T,O,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,T,O,W,W,T,T,W,W,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- bloated / macho ---
    private static let bloatedMacho: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [O,W,W,W,W,B,W,W,B,W,W,W,W,O,T,T],
            [O,W,W,W,W,W,W,P,W,W,W,W,W,O,T,T],
            [O,W,W,K,W,W,W,W,W,W,K,W,W,O,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,O,O,T,O,O,T,T,T,T,T,T,T,T],
            [T,T,O,W,W,O,O,W,W,O,T,T,T,T,T,T],
            [T,T,O,P,P,O,O,P,P,O,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [O,W,W,W,B,W,W,B,W,W,W,W,O,T,T,T],
            [O,W,W,W,W,W,P,W,W,W,W,W,O,T,T,T],
            [O,W,K,W,W,W,W,W,W,K,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,O,W,W,T,T,W,W,O,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [O,W,W,W,W,B,W,W,B,W,W,W,W,O,T,T],
            [O,W,W,W,W,W,W,P,W,W,W,W,W,O,T,T],
            [O,W,W,K,W,W,W,W,W,W,K,W,W,O,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,O,O,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,O,O,W,W,O,T,T,T,T],
            [T,T,T,T,O,P,P,O,O,P,P,O,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,W,W,O,T],
            [T,O,W,W,W,W,B,W,W,B,W,W,W,W,O,T],
            [T,O,W,W,W,W,W,W,P,W,W,W,W,W,O,T],
            [T,O,W,W,K,W,W,W,W,W,W,K,W,W,O,T],
            [T,T,O,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,W,W,W,T,T,W,W,O,T,T,T,T],
            [T,T,T,O,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [O,W,W,W,W,B,W,W,B,W,W,W,W,O,T,T],
            [O,W,W,W,W,W,W,P,W,W,W,W,W,O,T,T],
            [O,W,W,K,W,W,W,W,W,W,K,W,W,O,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ═══════════════════════════════════════════════════════
    // MARK: - STRESSED (Shaking, sweat drops, red marks)
    // ═══════════════════════════════════════════════════════

    // --- stressed / normal ---
    private static let stressedNormal: [[[UInt32?]]] = [
        // Frame 0: shake left, sweat
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,T,O,T,T,S,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,P,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,O,T,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,R,O,K,W,W,W,W,K,O,R,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,T,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: shake right, sweat drop
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,W,O,W,O,S,T,T,T,T],
            [T,T,T,T,T,T,O,P,O,P,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,W,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,T,O,W,B,W,W,B,W,O,T,T,T,T],
            [T,T,T,T,O,W,W,W,P,W,W,O,T,T,T,T],
            [T,T,T,R,O,K,W,W,W,W,K,O,R,T,T,T],
            [T,T,T,T,T,O,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,T,O,W,T,T,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: shake left
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,T,O,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,W,O,S,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,P,O,T,S,T,T,T,T,T],
            [T,T,T,T,O,W,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,T,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,O,W,B,W,W,B,W,O,T,T,T,T,T,T],
            [T,T,O,W,W,W,P,W,W,O,T,T,T,T,T,T],
            [T,R,O,K,W,W,W,W,K,O,R,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,T,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: shake right
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,O,T,O,T,S,T,T,T,T,T],
            [T,T,T,T,T,T,O,W,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,P,O,P,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,W,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,T,O,W,B,W,W,B,W,O,T,T,T,T],
            [T,T,T,T,O,W,W,W,P,W,W,O,T,T,T,T],
            [T,T,T,R,O,K,W,W,W,W,K,O,R,T,T,T],
            [T,T,T,T,T,O,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,T,O,W,T,T,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: shake center
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,S,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,R,O,K,W,W,W,W,K,O,R,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- stressed / buff ---
    private static let stressedBuff: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,O,O,T,S,T,T,T,T,T,T],
            [T,T,T,O,W,O,O,W,O,T,T,T,T,T,T,T],
            [T,T,T,O,P,O,O,P,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,O,W,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [R,O,W,K,W,W,W,W,W,K,O,R,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,O,W,W,T,T,W,W,O,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,S,T,T,T,T],
            [T,T,T,T,T,O,W,O,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,O,P,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,T,O,W,W,B,W,W,B,W,W,O,T,T,T],
            [T,T,T,O,W,W,W,W,P,W,W,W,O,T,T,T],
            [T,T,R,O,W,K,W,W,W,W,K,W,O,R,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,T,O,W,W,T,T,W,W,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,O,O,T,T,S,T,T,T,T,T],
            [T,T,T,O,W,O,O,W,O,T,T,S,T,T,T,T],
            [T,T,T,O,P,O,O,P,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,O,W,W,B,W,W,B,W,W,O,T,T,T,T,T],
            [T,O,W,W,W,W,P,W,W,W,O,T,T,T,T,T],
            [R,O,W,K,W,W,W,W,W,K,O,R,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,O,W,W,T,T,W,W,O,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,S,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,O,W,O,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,O,P,O,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,T,O,W,W,B,W,W,B,W,W,O,T,T,T],
            [T,T,T,O,W,W,W,W,P,W,W,W,O,T,T,T],
            [T,T,R,O,W,K,W,W,W,W,K,W,O,R,T,T],
            [T,T,T,T,O,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,T,O,W,W,T,T,W,W,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,S,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,R,O,W,K,W,W,W,W,K,W,O,R,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- stressed / macho ---
    private static let stressedMacho: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,O,O,T,S,T,T,T,T,T,T],
            [T,T,O,W,W,O,O,W,W,O,T,T,T,T,T,T],
            [T,T,O,P,P,O,O,P,P,O,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [O,W,W,W,B,W,W,B,W,W,W,O,T,T,T,T],
            [O,W,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [O,W,K,W,W,W,W,W,W,K,W,O,R,T,T,T],
            [R,O,W,W,W,W,W,W,W,W,O,R,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,O,W,W,T,T,W,W,O,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,T,S,T,T,T,T],
            [T,T,T,T,O,W,W,O,O,W,W,O,T,T,T,T],
            [T,T,T,T,O,P,P,O,O,P,P,O,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [T,T,O,W,W,W,B,W,W,B,W,W,W,O,T,T],
            [T,T,O,W,W,W,W,W,P,W,W,W,W,O,T,T],
            [T,T,O,W,K,W,W,W,W,W,W,K,W,O,R,T],
            [T,R,T,O,W,W,W,W,W,W,W,W,O,R,T,T],
            [T,T,T,T,O,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,T,O,W,W,T,T,W,W,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,O,O,T,O,O,T,T,S,T,T,T,T,T],
            [T,T,O,W,W,O,O,W,W,O,T,S,T,T,T,T],
            [T,T,O,P,P,O,O,P,P,O,T,T,T,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [O,W,W,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [O,W,W,W,B,W,W,B,W,W,W,O,T,T,T,T],
            [O,W,W,W,W,W,P,W,W,W,W,O,T,T,T,T],
            [O,W,K,W,W,W,W,W,W,K,W,O,R,T,T,T],
            [R,O,W,W,W,W,W,W,W,W,O,R,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,O,W,W,T,T,W,W,O,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,O,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,T,O,O,S,T,T,T,T,T],
            [T,T,T,T,O,W,W,O,O,W,W,O,T,T,T,T],
            [T,T,T,T,O,P,P,O,O,P,P,O,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,W,W,O,T,T],
            [T,T,O,W,W,W,B,W,W,B,W,W,W,O,T,T],
            [T,T,O,W,W,W,W,W,P,W,W,W,W,O,T,T],
            [T,T,O,W,K,W,W,W,W,W,W,K,W,O,R,T],
            [T,R,T,O,W,W,W,W,W,W,W,W,O,R,T,T],
            [T,T,T,T,O,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,T,O,W,W,T,T,W,W,O,T,T,T,T],
            [T,T,T,T,O,O,O,T,T,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,S,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,R,T,T],
            [R,T,O,W,W,W,W,W,W,W,W,O,R,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ═══════════════════════════════════════════════════════
    // MARK: - TIRED (Droopy ears, slow bob, half-closed eyes)
    // ═══════════════════════════════════════════════════════

    // --- tired / normal ---
    private static let tiredNormal: [[[UInt32?]]] = [
        // Frame 0: droopy
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,O,W,P,O,T,T,T,T,T],
            [T,O,P,W,O,O,O,O,W,P,O,T,T,T,T,T],
            [T,T,O,O,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,L,W,W,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: slight droop
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,O,P,W,O,O,O,O,W,P,O,T,T,T,T,T],
            [T,O,P,W,W,W,W,W,W,P,O,T,T,T,T,T],
            [T,T,O,O,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,L,W,W,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: head dip
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,O,W,P,O,T,T,T,T,T],
            [T,O,P,W,O,O,O,O,W,P,O,T,T,T,T,T],
            [T,T,O,O,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,L,W,W,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: slight droop
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,O,P,W,O,O,O,O,W,P,O,T,T,T,T,T],
            [T,O,P,W,W,W,W,W,W,P,O,T,T,T,T,T],
            [T,T,O,O,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,L,W,W,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: back up
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,T,T,T,T,O,O,T,T,T,T,T,T],
            [T,O,P,W,O,T,T,O,W,P,O,T,T,T,T,T],
            [T,O,P,W,O,O,O,O,W,P,O,T,T,T,T,T],
            [T,T,O,O,W,W,W,W,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,L,W,W,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,O,T,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,K,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- tired / buff ---
    private static let tiredBuff: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
            [T,O,P,P,W,O,T,O,W,P,P,O,T,T,T,T],
            [T,O,P,P,W,O,O,O,W,P,P,O,T,T,T,T],
            [T,T,O,O,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,L,W,W,L,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
            [T,O,P,P,W,O,O,O,W,P,P,O,T,T,T,T],
            [T,O,P,P,W,W,W,W,W,P,P,O,T,T,T,T],
            [T,T,O,O,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,O,W,W,L,W,W,L,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
            [T,O,P,P,W,O,T,O,W,P,P,O,T,T,T,T],
            [T,O,P,P,W,O,O,O,W,P,P,O,T,T,T,T],
            [T,T,O,O,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,L,W,W,L,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
            [T,O,P,P,W,O,O,O,W,P,P,O,T,T,T,T],
            [T,O,P,P,W,W,W,W,W,P,P,O,T,T,T,T],
            [T,T,O,O,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,O,W,W,L,W,W,L,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,O,O,O,T,T,T,T,T],
            [T,O,P,P,W,O,T,O,W,P,P,O,T,T,T,T],
            [T,O,P,P,W,O,O,O,W,P,P,O,T,T,T,T],
            [T,T,O,O,W,W,W,W,W,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,L,W,W,L,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,O,K,W,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,T,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- tired / macho ---
    private static let tiredMacho: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,T,O,O,O,T,T,T,T],
            [T,O,P,P,W,O,T,T,O,W,P,P,O,T,T,T],
            [T,O,P,P,W,W,O,O,W,W,P,P,O,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,L,W,W,L,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,T,O,O,O,T,T,T,T],
            [T,O,P,P,W,O,O,O,O,W,P,P,O,T,T,T],
            [T,O,P,P,W,W,W,W,W,W,P,P,O,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,L,W,W,L,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,T,O,O,O,T,T,T,T],
            [T,O,P,P,W,O,T,T,O,W,P,P,O,T,T,T],
            [T,O,P,P,W,W,O,O,W,W,P,P,O,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,L,W,W,L,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,T,O,O,O,T,T,T,T],
            [T,O,P,P,W,O,O,O,O,W,P,P,O,T,T,T],
            [T,O,P,P,W,W,W,W,W,W,P,P,O,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,L,W,W,L,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,O,O,O,T,T,T,T,O,O,O,T,T,T,T],
            [T,O,P,P,W,O,T,T,O,W,P,P,O,T,T,T],
            [T,O,P,P,W,W,O,O,W,W,P,P,O,T,T,T],
            [T,T,O,O,O,O,O,O,O,O,O,O,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,L,W,W,L,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ═══════════════════════════════════════════════════════
    // MARK: - COLLAB (Happy bounce, hearts/sparkle between)
    // ═══════════════════════════════════════════════════════

    // --- collab / normal ---
    private static let collabNormal: [[[UInt32?]]] = [
        // Frame 0: standing with hearts
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,P,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,P,P,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: hop, heart moves up
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,P,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,P,P,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: peak, heart high
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,P,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,P,P,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,T,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: descend, heart mid
        [
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,P,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,P,P,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,W,O,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: land
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,T,O,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,P,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,W,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,O,O,O,O,T,T,P,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,P,P,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,W,B,W,W,B,W,O,T,T,T,T,T],
            [T,T,T,O,W,W,W,P,W,W,O,T,T,T,T,T],
            [T,T,T,O,K,W,W,W,W,K,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,L,L,L,L,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,T,T,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
        ],
    ]

    // --- collab / buff ---
    private static let collabBuff: [[[UInt32?]]] = [
        // Frame 0
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,P,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,P,P,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,P,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,P,P,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,T,O,O,T,O,O,T,T,P,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,P,P,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,O,T,T,O,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,P,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,P,P,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,T,O,W,W,W,W,O,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,P,O,O,P,O,T,T,T,T,T,T],
            [T,T,T,T,O,W,O,O,W,O,T,T,T,T,T,T],
            [T,T,T,T,O,O,O,O,O,O,T,T,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,P,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,P,P,T,T,T],
            [T,T,O,W,W,B,W,W,B,W,W,O,T,T,T,T],
            [T,T,O,W,W,W,W,P,W,W,W,O,T,T,T,T],
            [T,T,O,W,K,W,W,W,W,K,W,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,O,L,L,L,L,L,L,O,T,T,T,T,T],
            [T,T,T,O,W,W,T,T,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,T,T,O,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // --- collab / macho ---
    private static let collabMacho: [[[UInt32?]]] = [
        // Frame 0: standing, sparkle + heart
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,Y,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,P,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,P,P,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 1: hop, sparkle shift
        [
            [T,Y,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,P,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,P,P,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: peak
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,Y,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,P,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,P,P,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,O,T,T,T,T,O,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: descend
        [
            [T,T,T,T,O,O,T,O,O,T,T,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,Y,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,P,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,P,P,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,O,T,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,T,O,W,W,W,W,W,W,O,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: land
        [
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
            [T,T,T,T,O,O,T,O,O,T,T,Y,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,P,P,O,O,P,P,O,T,T,T,T,T],
            [T,T,T,O,W,W,O,O,W,W,O,T,T,T,T,T],
            [T,T,T,O,O,O,O,O,O,O,O,T,T,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,P,T,T,T],
            [T,O,W,W,W,W,W,W,W,W,W,W,P,P,T,T],
            [T,O,W,W,W,B,W,W,B,W,W,W,O,T,T,T],
            [T,O,W,W,W,W,W,P,W,W,W,W,O,T,T,T],
            [T,O,W,K,W,W,W,W,W,W,K,W,O,T,T,T],
            [T,T,O,W,W,W,W,W,W,W,W,O,T,T,T,T],
            [T,T,O,L,L,L,L,L,L,L,L,O,T,T,T,T],
            [T,T,O,W,W,W,T,T,W,W,W,O,T,T,T,T],
            [T,T,O,O,O,O,T,T,O,O,O,O,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]
}
