import Foundation

// MARK: - Color Aliases

private let N: UInt32? = CLR_DBROWN   // Body dark brown
private let M: UInt32? = CLR_BROWN    // Body lighter brown
private let E: UInt32? = CLR_BEIGE    // Face / belly
private let B: UInt32? = CLR_BLACK    // Eye patches & eyes
private let C: UInt32? = CLR_CREAM    // Claws
private let P: UInt32? = CLR_PINK     // Nose
private let O: UInt32? = CLR_DBROWN   // Outline
private let Y: UInt32? = CLR_GOLD     // Macho sparkle
private let S: UInt32? = CLR_SKYBLUE  // Sweat
private let R: UInt32? = CLR_RED      // Stress
private let Z: UInt32? = CLR_GRAY     // Zzz
private let T: UInt32? = nil          // Transparent

// MARK: - SlothSprites

struct SlothSprites: SpriteProvider {

    static func frames(state: PetState, muscle: MuscleStage) -> [[[UInt32?]]] {
        switch muscle {
        case .normal: return normalFrames(state: state)
        case .buff:   return buffFrames(state: state)
        case .macho:  return machoFrames(state: state)
        }
    }

    // ================================================================
    // MARK: - Normal Muscle
    // ================================================================

    private static func normalFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return normalIdle
        case .normal:   return normalNormal
        case .busy:     return normalBusy
        case .bloated:  return normalBloated
        case .stressed: return normalStressed
        case .tired:    return normalTired
        case .collab:   return normalCollab
        }
    }

    // -- Normal / Idle (sleeping sloth, hanging from branch) --
    private static let normalIdle: [[[UInt32?]]] = [
        // Frame 1: hanging from branch, eyes closed, Zzz
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,Z,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,Z,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,Z],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: slight sway left
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,Z,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,E,P,P,E,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,T,N,N,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center again, Zzz higher
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,Z,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,Z,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,Z],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: slight sway right
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,E,P,P,E,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, Zzz reappears
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,Z,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Normal (hanging, droopy eyes, slow sway) --
    private static let normalNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,B,P,P,B,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,T,N,N,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, blink (half-closed eyes)
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,B,P,P,B,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, eyes open again
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Busy (hanging, arms moving, working) --
    private static let normalBusy: [[[UInt32?]]] = [
        // Frame 1: one arm reaching
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,C,C,N,M,M,M,M,N,C,C,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: both arms reaching out
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,C,C,N,N,N,N,N,N,N,N,C,C,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: arms close to body
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,C,N,N,N,N,C,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: right arm reaching
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,C,C,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: back to center
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Bloated (puffy belly, slow) --
    private static let normalBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left, bigger belly
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,E,P,P,E,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,M,M,M,M,M,M,N,N,T,T,T,T],
            [T,T,N,N,M,M,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,E,P,P,E,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,T,T,N,N,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Stressed (sweat, wide eyes, red tint) --
    private static let normalStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,S,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: shake left, sweat drops
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,S,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,R,P,P,R,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,T,N,N,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, eyes wide
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,S,T,T],
            [T,T,T,T,N,R,B,E,E,B,R,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: shake right
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,S,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,R,P,P,R,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, sweat falling
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,S,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,S,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Tired (droopy everything, yawning) --
    private static let normalTired: [[[UInt32?]]] = [
        // Frame 1: droopy, half eyes
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: yawn opening
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: full yawn
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,P,P,P,P,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: yawn closing
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: back to droopy
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Normal / Collab (two-armed wave, happy) --
    private static let normalCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,C,C,N,M,M,M,M,N,C,C,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: left arm wave
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,C,C,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,C,C,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: both arms up
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,C,C,N,N,M,M,M,M,N,N,C,C,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: right arm wave
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,C,C,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,C,C,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: both arms out
        [
            [T,T,T,T,N,N,N,N,N,N,N,N,T,T,T,T],
            [T,T,T,C,C,T,T,T,T,T,T,C,C,T,T,T],
            [T,T,T,C,N,T,T,T,T,T,T,N,C,T,T,T],
            [T,T,T,N,N,T,T,T,T,T,T,N,N,T,T,T],
            [T,T,T,N,M,T,T,T,T,T,T,M,N,T,T,T],
            [T,T,T,T,M,N,N,N,N,N,N,M,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,N,N,T,T,T,T,T],
            [T,T,T,C,C,N,M,M,M,M,N,C,C,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ================================================================
    // MARK: - Buff Muscle
    // ================================================================

    private static func buffFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return buffIdle
        case .normal:   return buffNormal
        case .busy:     return buffBusy
        case .bloated:  return buffBloated
        case .stressed: return buffStressed
        case .tired:    return buffTired
        case .collab:   return buffCollab
        }
    }

    // -- Buff / Idle (bigger arms, sleeping) --
    private static let buffIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,Z,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,Z,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,Z],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,Z,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,E,P,P,E,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,T,N,T,N,N,N,N,N,N,T,N,T,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, Zzz
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,Z,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,Z,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,Z],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,E,P,P,E,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,N,T,N,N,N,N,N,N,T,N,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, Zzz
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,Z,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Normal (thicker arms, hanging) --
    private static let buffNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,B,P,P,B,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,T,N,T,N,N,N,N,N,N,T,N,T,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, blink
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,B,P,P,B,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,N,T,N,N,N,N,N,N,T,N,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Busy (thick arms typing) --
    private static let buffBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,C,C,T,N,M,M,M,M,N,T,C,C,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: arms wide
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,C,C,N,T,N,N,N,N,N,N,T,N,C,C,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: arms close
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,C,N,M,M,M,M,N,C,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: right arm reach
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,N,C,C,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Bloated (thick + puffy) --
    private static let buffBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,E,P,P,E,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,M,M,M,M,M,M,N,N,T,T,T,T],
            [T,T,N,N,M,M,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,E,P,P,E,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,M,M,N,N,T,T],
            [T,T,T,T,N,N,M,M,M,M,M,M,N,N,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Stressed --
    private static let buffStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,S,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,T,T,T,T,T],
            [T,S,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,R,P,P,R,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,T,N,T,N,N,N,N,N,N,T,N,T,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,S,T,T],
            [T,T,T,T,N,R,B,E,E,B,R,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,T,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,S,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,R,P,P,R,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,N,T,N,N,N,N,N,N,T,N,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,S,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,S,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Tired --
    private static let buffTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: yawn
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: full yawn
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,P,P,P,P,E,N,T,T,T,T],
            [T,T,T,N,N,E,E,P,P,E,E,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: closing
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: droopy
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Buff / Collab (arm wave with thick arms) --
    private static let buffCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,C,C,T,N,M,M,M,M,N,T,C,C,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: left wave
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,C,C,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,N,C,C,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: both up
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,C,C,N,N,N,M,M,M,M,N,N,N,C,C,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: right wave
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,C,C,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,C,C,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: both out
        [
            [T,T,T,N,N,N,N,N,N,N,N,N,N,T,T,T],
            [T,T,C,C,N,T,T,T,T,T,T,N,C,C,T,T],
            [T,T,C,N,N,T,T,T,T,T,T,N,N,C,T,T],
            [T,T,N,N,N,T,T,T,T,T,T,N,N,N,T,T],
            [T,T,N,N,M,T,T,T,T,T,T,M,N,N,T,T],
            [T,T,T,N,M,N,N,N,N,N,N,M,N,T,T,T],
            [T,T,T,T,N,N,M,M,M,M,N,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,T,N,N,N,N,N,N,T,N,T,T,T],
            [T,T,C,C,T,N,M,M,M,M,N,T,C,C,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // ================================================================
    // MARK: - Macho Muscle
    // ================================================================

    private static func machoFrames(state: PetState) -> [[[UInt32?]]] {
        switch state {
        case .idle:     return machoIdle
        case .normal:   return machoNormal
        case .busy:     return machoBusy
        case .bloated:  return machoBloated
        case .stressed: return machoStressed
        case .tired:    return machoTired
        case .collab:   return machoCollab
        }
    }

    // -- Macho / Idle (absurdly jacked, sleeping) --
    private static let machoIdle: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,Z,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,Z,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,Z],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,Y,T,N,B,E,E,E,E,B,N,T,T,T,Z,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,E,P,P,E,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,N,N,N,N,T,T,T],
            [T,T,N,T,N,N,N,N,N,N,T,N,N,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, Zzz
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,Z,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,Z],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,Y,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,E,P,P,E,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,N,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,N,N,T,N,N,N,N,N,N,T,N,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,Z,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Macho / Normal (jacked but glacial, sparkles) --
    private static let machoNormal: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [Y,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,B,P,P,B,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,N,N,N,N,T,T,T],
            [T,T,N,T,N,N,N,N,N,N,T,N,N,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, blink, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,Y,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,Y],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,B,P,P,B,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,N,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,N,N,T,N,N,N,N,N,N,T,N,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [Y,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Macho / Busy (absurd muscles working) --
    private static let machoBusy: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,C,C,T,T,N,M,M,M,M,N,T,T,C,C,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: arms wide, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,N,N,N,N,N,M,M,M,M,N,N,N,N,N,T],
            [C,C,N,N,T,N,N,N,N,N,N,T,N,N,C,C],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,Y,T,T,T,T,N,N,N,N,T,T,T,T,Y,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: arms close
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,C,N,M,M,M,M,N,C,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: right arm reach, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [Y,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,N,N,C,C],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,Y],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Macho / Bloated (huge belly + huge arms) --
    private static let machoBloated: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,M,M,N,N,N,T,T],
            [T,T,N,N,N,M,M,M,M,M,M,N,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: sway left
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,E,P,P,E,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,M,M,M,M,M,M,N,N,N,T,T,T],
            [T,T,N,N,M,M,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,M,M,N,N,N,T,T],
            [T,Y,N,N,N,M,M,M,M,M,M,N,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: sway right
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,T,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,E,P,P,E,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,N,N,N,M,M,M,M,M,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,M,M,N,N,Y,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,M,M,N,N,N,T,T],
            [T,T,N,N,N,M,M,M,M,M,M,N,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Macho / Stressed (jacked + panicking) --
    private static let machoStressed: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,S,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: shake left, sweat
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,M,M,M,M,N,N,N,T,T,T,T],
            [S,T,T,N,B,E,E,E,E,B,N,T,T,T,T,T],
            [T,T,T,N,B,B,E,E,B,B,N,T,T,T,T,T],
            [T,T,T,N,E,R,P,P,R,E,N,T,T,T,T,T],
            [T,T,T,N,E,E,E,E,E,E,N,T,T,T,T,T],
            [T,T,N,N,N,M,M,M,M,N,N,N,N,T,T,T],
            [T,T,N,T,N,N,N,N,N,N,T,N,N,T,T,T],
            [T,T,T,T,N,M,M,M,M,N,T,T,T,T,T,T],
            [T,T,T,T,T,N,N,N,N,T,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: center, eyes wide
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,S,T,T],
            [T,T,T,T,N,R,B,E,E,B,R,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: shake right
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,T,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,T,T,N,B,E,E,E,E,B,N,T,S,T],
            [T,T,T,T,T,N,B,B,E,E,B,B,N,T,T,T],
            [T,T,T,T,T,N,E,R,P,P,R,E,N,T,T,T],
            [T,T,T,T,T,N,E,E,E,E,E,E,N,T,T,T],
            [T,T,T,N,N,N,N,M,M,M,M,N,N,N,T,T],
            [T,T,T,N,N,T,N,N,N,N,N,N,T,N,T,T],
            [T,T,T,T,T,T,N,M,M,M,M,N,T,T,T,T],
            [T,T,T,T,T,T,T,N,N,N,N,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: center, sweat falling
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,R,P,P,R,E,N,S,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,S,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Macho / Tired (huge muscles, yawning glacially) --
    private static let machoTired: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: yawn start
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: full yawn, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [Y,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,P,P,P,P,E,N,T,T,T,T],
            [T,T,N,N,N,E,E,P,P,E,E,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: closing
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,Y],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: droopy, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,E,P,P,E,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,Y,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]

    // -- Macho / Collab (jacked arm waves, sparkles everywhere) --
    private static let machoCollab: [[[UInt32?]]] = [
        // Frame 1
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,C,C,T,T,N,M,M,M,M,N,T,T,C,C,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 2: left wave, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [Y,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [C,C,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,N,N,C,C],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 3: both up, sparkles
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [Y,T,T,N,N,N,M,M,M,M,N,N,N,T,T,Y],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [C,C,N,N,N,N,M,M,M,M,N,N,N,N,C,C],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,T,T,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 4: right wave, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,Y],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [T,T,T,T,N,B,E,E,E,E,B,N,T,T,T,T],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,C,C],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,C,C,T,T,N,M,M,M,M,N,T,T,T,T,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
        // Frame 5: both out, sparkle
        [
            [T,T,N,N,N,N,N,N,N,N,N,N,N,N,T,T],
            [T,C,C,N,N,T,T,T,T,T,T,N,N,C,C,T],
            [T,C,N,N,N,T,T,T,T,T,T,N,N,N,C,T],
            [T,N,N,N,N,T,T,T,T,T,T,N,N,N,N,T],
            [T,N,N,N,M,T,T,T,T,T,T,M,N,N,N,T],
            [T,T,N,N,M,N,N,N,N,N,N,M,N,N,T,T],
            [T,T,T,N,N,N,M,M,M,M,N,N,N,T,T,T],
            [Y,T,T,T,N,B,E,E,E,E,B,N,T,T,T,Y],
            [T,T,T,T,N,B,B,E,E,B,B,N,T,T,T,T],
            [T,T,T,T,N,E,B,P,P,B,E,N,T,T,T,T],
            [T,T,T,T,N,E,E,E,E,E,E,N,T,T,T,T],
            [T,T,N,N,N,N,M,M,M,M,N,N,N,N,T,T],
            [T,T,N,N,T,N,N,N,N,N,N,T,N,N,T,T],
            [T,C,C,T,T,N,M,M,M,M,N,T,T,C,C,T],
            [T,T,T,T,T,T,N,N,N,N,T,T,T,T,T,T],
            [T,T,T,T,T,T,T,T,T,T,T,T,T,T,T,T],
        ],
    ]
}
